keogram.cpp, startrails.cpp
Noticed that if I stop the capture process during the night that causes some empty files which then later crashed the keogram and startrail processes with OpenCV exception.  So skip those files and continue with the rest.
=> Skip corrupt image files correctly

.clang-format, capture.cpp, keogram.cpp, startrails.cpp
Create consistent code formatting so that it is easier to read and understand.  Only changes made are code formatting only.  Applied to all three cpp files.   
Includes `clang-format` config file that can be used by installing clang-format via `sudo apt-get install clang-format`. When you make code changes you can if you wish make sure your formatting matches by executing `clang-format -i capture.cpp` as example.
**Note**: Argument parsing can be cleaned up after this PR so that is isn't as verbose looking.  Wanted to keep this to zero actual code change PR.
=> Fix code formatting 

startrails.cpp
The statistics vector seems to be zero initialized and if there was an error reading an image I didn't set any value a mean before so in case no frames were darker than threshold, one of these frames was picked as minimum value. The fix is to mark mean value as 1.0 so they don't get picked as minimum frames.
=> Fix startrails generation when read error and no dark enough images

allsky.sh
* Added check to allsky.sh to ensure a ZWO device is plugged in prior to attempting to start capture.
* If it is not present, stop the systemd allsky unit and exit gracefully with a friendly message.
=> Added check in allsky.sh to ensure a ZWO device is present

capture.cpp
New Raspbian installs are now using Debian Buster with OpenCV 3.2 which doesn't like the old style IplImage calls anymore, which were deprecated in OpenCV 3.0. So updated the code to use OpenCV 2 style Mat calls and this code compiles with both 2.4 in Stretch and 3.2 in Buster. I hope I haven't broken anything, as I could only test with my 120MM-S so not sure about color cameras.
Also ran through clang-format to unify the styling, causing some diff noise unfortunately.
=> Update OpenCV calls to OpenCV2 style for Buster

capture.cpp, settings.json.repo
Depending on your camera, color scheme, mono/rgb capture, lighting conditions, etc... you might have a hard time reading the overlay text.
This diff adds an option - `outlinefont` - to simply add a thin black border around the text to improve its contrast. If this diff is accepted, I'll do up a corresponding change for the web UI.
Here's what that looks like on a white frame:
And here's what that looks like on an actual capture:
Or in the evening:
=> allow for an outline font. might improve text readability

keogram.cpp, startrails.cpp
As per comment for startrails.cpp, the fix there caused a possible use-after-free situation and could be done even earlier. Also added similar check to keogram.cpp so we don't produce empty image in case there are no source files.
=> Fix early exit in case no files are found

capture.cpp
capture.cpp:882:28: warning: format not a string literal and no format arguments [-Wformat-security]
found while I was setting up to build and run on x86_64
=> silence format string warning

scripts/timelapse.sh
The `-movflags +faststart` option to `ffmpeg` creates the mp4 file such that the file's movie ("MOOV") atom, the bit of metadata that  describes the movie's data, appears at the beginning of the file instead of the end. This allows playback to begin once sufficient frame data is downloaded instead of until the entire mp4 file is downloaded, as the MOOV atom is usually placed at the end because it contains data that is known only once the entire movie is encoded.
=> Add faststart to ffmpeg command line

README.md, capture.cpp
Allows greyscale colours to be used on RAW16 images. The normal colour settings are used but only the B & G values. The R value MUST be 0.
So white would be 255 255 0 and a lighter grey 255 128 0
Also needs a change making to the UI to amend the help text for the camera config?
=> Fix for font colours on RAW16 Images

gui/lighttpd.conf
Fixes lighttpd.conf so that the server transmits the MIME type of the css files correctly.
Some browsers will otherwise not load the css files and the webpage will not be displayed correctly.
=> Fix MIME-type for css files

scripts/endOfNight.sh
Both `keogram` and `startrails` set JPEG and PNG compression parameters, and `cv::imwrite` chooses the image format based on the filename. If the user has chosen an image format, then let's use it in all the nightly steps
=> be more consistent in the use of EXTENSION

README.md, capture.cpp
Adds three new fields to the camera config (To be used in conjunction with the PR on the allsky-portal repo)
- extratext - The full path to a file containing the extra text to be displayed on the images. The file can contain multiple lines, each will be displayed.
- extratextage - If the file above is not updated within this timeframe then the contents of the text file will not be added to the images, handy for when the process updating the text file crashes. To disable this check set the value to 0
- textlineheight - Allows the line height of the text to be changed, saves people manually editing and recompiling capture.cpp
- Fixed a few issues with name and std library clashes (renamed time to showTime)
- Fixed a bug with the command line parser if a text value was missing
- Added a …
=> Added extra text options

scripts/uploadForDay.sh
The uploadForDay script had the following issues
1) Does not include the ftp settings so could never connect
2) The file extension was hard coded to .jpg
=> Fix ftp and filename issues in upload script

README.md, gui/install.sh
Since I have multiple installations I needed a way to prevent the gui nameing all of them 'allsky'.
This change allows the hostname to be specified when installing the GUI. If no name is specified then the default 'allsky' is used.
Tested on a clean pi after installing allsky. Also re run the gui installer several times to confirm the hostname changes correctly.
=> Allow name of Pi to be specified for GUI install

allsky.sh, autocam.sh, autostart/allsky.service, config.sh.repo
e.g. useful for faster/easier setup using defaults, or if one has both cameras as uses headless mode. 
@thomasjacquin 
RPI camera is pretty bad, so quite obviously default should be ZWO.
seem to work ok.
=> Add camera auto-select mode

config.sh.repo, scripts/saveImageDay.sh, scripts/saveImageNight.sh
Hi Thomas,
Files of the Pi HQ cam are quite large (about 5+ MB). First, I tried the 2x2 binning option so save some space but that generated quite strange artifacts and especially a hot pixel that is not there when not using binning. You can get rid of it with dark frame subtraction, but only for some time - it seems to move and then leaves a black spot with a new hot pixel next to it in the binned image.
As this effect doesn't occur when using the full resolution (1x1 binning) and I even don't have hot pixels at all in that mode (on-chip dead-pixel correction is switched on), I added an option to scale down the picture before saving it in the daily folder. Reducing the image size by a factor of 2 leaves me with individual images of around 1,3 MB each - and with no artifacts or hot …
=> Added scaling option to save disk space

README.md
and other minor changes.  Several Pi 3 users were not able to create timelapse videos until they increased their swap space.
=> Mention creating swap space

README.md, allsky.sh, capture.cpp, settings_ZWO.json.repo, website/install.sh
README.md was referring to "settings.json" rather than "settings_ZWO.json" and "settings_RPiHQ.json".
=> Fixed # 442

README.md, capture.cpp
Based on code update provided in [comment](https://github.com/thomasjacquin/allsky/issues/417#issuecomment-906830896) by [EricClaeys](https://github.com/EricClaeys).  This allows reverting back to the 'v7' exposure method fixing [issue 417](https://github.com/thomasjacquin/allsky/issues/417).
Includes README.md documentation of the option.
=> Add -newexposure option based on issue 417

capture.cpp
These lines should have been removed in the fix to # 417.
=> Removed start/stop video lines - bug fix

.gitignore
Want the camera config json files to stop showing up as untracked files.
=> Ignore settings_*.json

Makefile
First, create some generic CFLAGS, with some warnings and optimizations. Do the same for some macros.
Then the platform-specific configurations run, appending to CFLAGS, ZWOSDK, and DEFS as appropriate.
Finally, combine these into the actual CFLAGS that will be passed to the compiler. Found while wondering why "-O2" wasn't working for me.
Also removed `$(COMMON)` which wasn't defined anywhere and I suspect was copied from the ZWO SDK example makefile, and added a note to the armv7 section about maybe switching to opencv4.
=> move CFLAGS and DEFS definitions

capture.cpp, capture_RPiHQ.cpp
Dunno what `Â` is, but it's not a `µ`. Maybe we should revert to `us` as an approximation for microseconds and `um` for micrometers because those are easy to type/display in 7-bit ASCII.
=> remove some junk characters

capture.cpp
New exposure mode did not correctly set the capture ROI if the image size was manually specified. It was calling SetROI with a 0x0 window which would cause subsequent captures to fail.
At least partially fixes #471 
cc @EricClaeys
=> unbreak ROI selection

capture.cpp
Doing a bunch of USB disk IO was killin' the capture on my rPi. Bumping
up to 1500ms allowed capture to run successfully while copying lots of
data.
=> increase USB timeout

capture.cpp
This was left out of the fix implemented a couple weeks ago.  Without this change, people using the version 0.7 exposure method will get failures.
=> Turn on video mode for 0.7 exposure method

capture.cpp
At least this way I know when the trash frame exposures fail, and why... rather than getting a silent failure
=> emit debug message when buffer clearing fails

config.sh.repo, scripts/timelapse.sh
`rm -rf /tmp/nonexistent` doesn't fail on nonexistent files, so unconditionally nuke the sequence directory
```
$ rm -rf /tmp/nonexistent && echo that worked
that worked
```
provide some default values for the framerate and encoder, just in case you don't have them in your configs.
=> Make it easier to reprocess images on other machines

keogram.cpp, scripts/endOfNight.sh, startrails.cpp
This set of commits switches command line argument parsing to use `getopt(3)`.
Arguments such as directory, image extension, and output are now handled using command line flags (guess what `-d`, `-e`, and `-o` do), which makes them position insensitive.
I've added some helpful sensible defaults, eg. if you ask to use a nonexistent font for keograms, you get a warning about that, and the program proceeds to use the `SIMPLEX` font. Keogram font color is now specified as a single hex value string, like colors in HTML, leading `#` is optional, so you can say something like `-C ff0000` or `--font-color '#ff0000'`, whatever you prefer. These don't appear to be used in `endOfNight.sh`
A help screen is also available with `-h` or `--help`. If argument errors are detected, the utility exits with …
=> Silence aux tools

capture.cpp
During compile a warning is issued for a possibly uninitialized variable.  This is due to the declaration of these variables having no value, and no default 'else' is present to set them should none of the conditional tests match.
Added 0 and 0.0 values to the declaration of these variables to remove the compile warning.
```
capture.cpp: In function ‘int main(int, char**)’:
capture.cpp:2187:33: warning: ‘num’ may be used uninitialized in this function [-Wmaybe-uninitialized]
sprintf(textBuffer, "  > !!! Retrying @ %'ld us because '%s (%d)'\n", currentExposure, why.c_str(), num);
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
capture.cpp:2094:48: warning: ‘exposureAdjustment’ may be used uninitialized in this function …
```
=> Initialize num and exposureAdjustment values to 0

README.md, install.sh
- Removed need to run script with `sudo`.
- This fixes incorrect `root` user being applied to systemd and other locations.
- Changed systemd install path to /etc since this is user provided, not system
- Changed to use `install` commands instead of `cp`/`chmod`/`chown` dances
- Changed to `apt` from `apt-get` for better user experience
- Changed references to `logname` to `$USER`
- Make copying of `*.repo` files conditional on non-existence of target.
=> Installer tweaks

keogram.cpp, startrails.cpp
This depends on the previous PR to add getopt. Now that I have getopt, it's easy to add extra flags to do useful things, like filtering improperly sized images to avoid opencv assertion failures.
=> Fix opencv crash

install.sh
Resolves #514 
There was one missing sudo, but it wasn't the full contributor to all the errors.  Looks like the local git repo was owned by root, but the compile / install was tried as regular user.  Regular user `install.sh` will work, but the git repo must be owned by that user.
=> Fixed missing sudo on sed /etc/xdg/lxsession/LXDE-pi/autostart

scripts/copy_notification_image.sh, scripts/endOfNight.sh, scripts/generateForDay.sh, scripts/postData.sh, scripts/saveImageDay.sh, scripts/saveImageNight.sh, scripts/timelapse.sh, scripts/upload.sh, scripts/uploadForDay.sh, variables.sh
Moved all the upload-related code from several files to a new file called "upload.sh".  This file can be executed manually, allowing users to debug upload (mostly lftp) issues.
As part of this Pull Request, a new file called "variables.sh" was added that sets several variables used by scripts.  For example, ALLSKY_SCRIPTS to point to the allsky/scripts directory, and ALLSKY_TMP to point to allsky/tmp.  Having these are variables will allow us to easily move them in the future.
=> Centralized upload

scripts/copy_notification_image.sh
This causes all Notification Image uploads to fail, leaving an "NI-*" file on the remote server.
=> copy_notification_image.sh: fix IMG_DIR bug

scripts/endOfNight.sh
Probable fix for #547 and #539
=> add filtering on image size to startrail and keogram generation

allsky.sh, config_repo/config.sh.repo
Fixed in two steps:
- If `CAMERA` is still set to `auto` after reading `autocam.sh` from `config.sh`, don't try to read the camera settings, instead set default debug level 0.
- In `allsky.sh`, if auto camera detection was selected, and we detect a camera, re-read debug level from the proper camera settings file.
=> Fixes 'jq' try to read settings_auto.json warning in logs

scripts/ftp-settings.sh.repo
`endOfNight.sh` was using a variable `VIDEOS_DIR` which was not defined.  Updated `ftp-settings.sh.repo` to match the expectations of `endOfNight.sh`.
Resolves #552
=> Renamed MP4DIR to VIDEOS_DIR to match endOfNight.sh expectation

allsky.sh
Allows all called scripts from `capture` to not need anything from `variables.sh`, thus the multi-loading guard in place in `variables.sh` will prevent unneeded extra work.
=> Have allsky.sh call variables.sh before starting capture

src/keogram.cpp, src/startrails.cpp
In the spirit of unix, "no news" is good news. Recoverable errors are not printed because there's no action required from the user.
If a single `-v` is given, then more diagnostics are emitted, including recoverable error (file name, error type, resolution).
If multiple `-v` are given, every file is printed as it is processed.
Finally, if no `-v` are given, then the value of the `ALLSKY_DEBUG_LEVEL` environment variable is used.
related to #539
=> tune output of diagnostic messages.

scripts/postData.sh
DAYTIME is old name, DAYTIME_CAPTURE is new name (and it uses true/false instead of 0/1).
Until the new config.sh is fully deployed, check for both variables.
=> postData.sh: fix DAYTIME_CAPTURE bug

scripts/endOfNight.sh, src/startrails.cpp
Also, make the size filter consistent: `-s`. Because of that, hoist the size filter argument generation up to where the filter parameters are computed with jq.
=> Implement long options for startrails

scripts/upload.sh
This avoid additional, confusing error messages after the first one.
=> Exit upon first error in lftp

install.sh
If not run from $ALLSKY_HOME it would not find variables.sh and give an error.  This PR fixes that.
It also puts the "NOT run as root" error message in red.
=> install.sh - avoid error messages

scripts/upload.sh
Had the and/or logic wrong so lftp wasn't exiting when it should, which produces additional, confusing error messages.
=> upload.sh: bug fix with failures

src/capture.cpp
This PR replaces the one with only a few commits.
This PR has a bunch of commits, each with fewer changes to make it easier to read.
=> Capture.cpp changes

scripts/copy_notification_image.sh, scripts/darkCapture.sh, scripts/generateForDay.sh, scripts/timelapse.sh
=> Scripts changes

scripts/endOfNight.sh
variables.sh sets $RED and other colors, and needs to be called before using $RED in the usage error message.
This change simply reorders the first 25 lines.
=> endOfNight.sh: source variables.sh first

src/capture_RPiHQ.cpp, src/keogram.cpp, src/startrails.cpp
1. new parameter -x (expands image to get the proportions of source)
2. new parameter -c (show channel infos - mean value)
3. text with black background
4. show date
5. calculate mean value only in the inner circle (mask) - without steetlights, cars,... 
./keogram_li -d images/20211031 -e jpg -o test_li.jpg -x -c
daylight saving:
without changes:
=> Keogram li

scripts/removeBadImages.sh
Allow a file to be specified and only process that file.
Disable low threshold if image is a dark frame.
Check that specified directory (and file) exists.
Save output in temp file & output message to look in temp file if anything's there.
=> removeBadImage.sh: misc changes/fixes

scripts/darkSubtract.sh
The "convert" command is smart enough to determine what bit depth the output file should be based on the input file and the dark file, so we don't need to force TrueColor (24 bit).  This causes problems because daytime mono images are 8-bit (no dark subtraction is done) but nighttime images are 24-bit.
=> darkSubtract.sh: don't force -type TrueColor

src/Makefile
Resolves #749 
Removed `check_deps` from individual compile targets.  Left it as part of `all` so it will still occur during normal install.
=> Fixed repeated recompile when no source change

website/install.sh
No longer require WebUI to be installed.  Instead, prompts the user.
Replace the XX_ALLSKY_CONFIG_XX placeholder in $WEBSITE_DIR/functions.php.
Automatically update computer, latitude, longitude, and auroraMap in $WEBSITE_DIR/config.js.
Support an "--update" option.  Doesn't do much now, but can do more in the future.
=> install.sh: replace XX_ALLSKY_CONFIG_XX, and more

config_repo/config.sh.repo, scripts/endOfNight.sh, scripts/generateForDay.sh, scripts/timelapse.sh, scripts/upload.sh
Merged the upload code from endOfNight.sh into generateForDay.sh since they were doing almost identical things.
Consolidated code in generateForDay.sh into a couple internal functions to further reduce redundancy.
Other consistency and simplification changes.
=> Remove duplicate upload code

gui/install.sh, gui/sudoers
so it can execute the vcgencmd command (new "show throttling" view on the "System" page).
There is a separate PR for the allsky-portal portion of this change.
=> gui/install.sh: add www-data to "sudo" group

gui/install.sh, gui/sudoers
Update /etc/sudoers.d/allsky if needed and possible.
Added banner for updates.
Move SCRIPTPATH up since it's needed higher in file now.
=> gui/install.sh: update sudoers with vcgencmd

scripts/postData.sh
IMGDIR is the old name; IMAGE_DIR is the new name so use it.
Use $DAYTIME_CAPTURE which is either "true" or "false"
Other changes are mostly cosmetic.
=> postData.sh: use IMAGE_DIR

src/capture_RPiHQ.cpp
The relationship between ZWO gain (unit 0.1 dB) and gain should be reviewed.
My guess: gain = 10 ^ (ZWO gain / 20)
In the future, the ZWO control should also use the exposure time and gain
for allsky the pictures should be the same with these settings:
10s, ZWO gain 200
100s, ZWO gain 0
60s, ZWO gain 73
Can someone test this for me with a ZWO camera?
=> Cleanup: ZWO gain=0.1 dB , RPiHQ gain=factor

scripts/darkCapture.sh
%2f produced files with leading spaces, which broke darkSubtract.sh
No need for 3-digit temps since they are in Celsius and if someone has 100+ C sensor it'll fry.
=> darkCapture.sh: always output 2-digit temp

scripts/darkSubtract.sh, variables.sh
When a file is "source"d into another, $0 in the "source"d file takes the name of the invoking script.
Using BASH_SOURCE[0] in the invoked script prints its name.
=> Use BASH_SOURCE[0] instead of $0

src/capture.cpp, src/capture_RPiHQ.cpp
The "extra text" file hasn't yet been fully implemented in the RPiHQ capture program, but variables to activate it are there.  This causes compiler messages about "variable set but not used".  This is not an issue, but some users have mentioned it, thinking it's an error.
I added a dummy line to keep the compiler quiet.  This line will be removed when the "extra text" file is implemented.
Fixes #833.
=> capture_RPiHQ.cpp: compiler warning

src/capture_RPiHQ.cpp
The --info_text option only exists in libcamera.
=> capture_RPiHQ.cpp: fix info_text

scripts/generateForDay.sh
$TIMELAPSE_EXTRA_PARAMETERS should NOT be passed to timelapse.sh since it's in config.sh and is already on the command line for ffmpeg in timelapse.sh.
Fixes #866
=> generateForDay.sh: bug in args to timelapse.sh

scripts/generateForDay.sh
Only show the "upload" message if file creation worked, i.e., $EXIT_CODE = 0.
=> generateForDay.sh: upload message fix

scripts/postData.sh
Use the user Angle instead of "civil" twilight which assumes an angle of -6.
Copy the data.json file to the website on the Pi, if it exists.  This is needed so the local website knows when daylight is and can display the aurora forecast picture if daytime images are not being taken.
Warn the user if their angle results in an unknown sunset time from sunwait.
Warn the user if there is no local website and no remote host to copy the file to.
Improve comments.
=> postData.sh: fix inaccuracy

src/capture.cpp, src/capture_RPiHQ.cpp
png is lossless so "quality" is really just the amount of compression.  Since dark frames stick around a long time, compress them at the max setting (9) rather than the min (0).
=> Png compression

src/capture_RPiHQ.cpp
With just %3d it would put a space in the argument value which saveImage,sh treated as two arguments instead of one.
=> Capture_RPiHQ.cpp: use %03d

scripts/saveImage.sh
When not saving daytime images, image.jpg wasn't getting updated.
=> SaveImage.sh bugfix - creating image.jpg

scripts/saveImage.sh
The current image gets moved into ${WORKING_DIR}/${FULL_FILENAME} before it is uploaded to the server. During the upload the image then cannot be found and an error is thrown.
**Solutions**
- I just copied (instead of moved) the image away into ${WORKING_DIR}/${FULL_FILENAME}
- another solution would be to set ${IMAGE_TO_USE} to ${WORKING_DIR}/${FULL_FILENAME} but then the timestamp within the filename is lost.
=> Image not available when uploading to server

scripts/upload.sh
Moved some code only used by FTP protocol into that section.
For debugging, added $TEMP_NAME to debug output.  On very slow networks it's possible for multiple lftp's to be happening at once, which can cause problems.  Adding $TEMP_NAME helps debug that.  Really should only allow one lftp per file, e.g., one for "image.jpg".
If a password has "!!" in it, it's interpreted as shell job history, so use "set +H" to turn that off.  Really want to disable ALL special character processing in ${REMOTE_PASSWORD}, but don't know how.
=> upload.sh: minor changes

scripts/darkSubtract.sh, src/capture.cpp, src/capture_RPiHQ.cpp
Bash treats numbers with a leading 0 as octal, so if we try to convert the string "09" to an integer it'll complain that "9" isn't an octal number.  So, don't pass numbers to saveImage.sh with leading zero's.  If saveImage.sh or another script want a fixed length number, it can create it in the desired format.  For example, "9" can be converted to "09".
This bug breaks anyone with dark images taken when the sensor is either 8 or 9 degrees (which happened).
=> Remove leading zeros

scripts/endOfNight.sh
Add completion messages to log to make it easy to see when the commands finished.
=> endOfNight.sh: aid in debugging

src/startrails.cpp
When troubleshooting users' issues we tell them to set Debug Level to 4, which sets ALLSKY_DEBUG_LEVEL to 4.  We almost never want debug output from startrails.cpp, especially one line for each images (potentially thousands) cluttering up the log file.
If we, or users, want debug output from startrails.cpp they can add "--verbose" to STARTRAILS_EXTRA_PARAMETERS.
=> startrails.cpp: remove ALLSKY_DEBUG_LEVEL

website/install.sh
This PR lets users install updates to the Allsky website via `~/allsky/website/install.sh`.  It saves their timelapse, keograms, startrails, and configuration files, then restores them after the update.
=> Allow web install over prior version

src/keogram.cpp
avoids: https://github.com/thomasjacquin/allsky/issues/979
solves: https://github.com/thomasjacquin/allsky/issues/980
=> bug: set minimum value for parameter font-line, description for parse-filename

src/Makefile
With this flag all warning are changed into errors.
The main advantage is that the automatic test (action) now immediately alerts us to warnings
If warnings cannot be avoided, this can be switched off in the source code if necessary.
=> cleanup: use -Werror

scripts/saveImage.sh, src/Makefile, src/sunwait.patch
Upstream PRs [sunwait#24](https://github.com/risacher/sunwait/pull/24) and [sunwait#29](https://github.com/risacher/sunwait/pull/29) have sat for 30+ days with no action.  Patching here to clean up our compile messages.
=> Patching sunwait to clear compile warnings

variables.sh
variables.sh is sourced into other scripts which already set $ME.  Don't overwrite that.
=> variables.sh: don't overwrite $ME

scripts/darkCapture.sh
Move the dark file to the darks directory rather than copy it.
If the user isn't using notification images, copy the file back to tmp/image.jpg so the websites can see it.
=> darkCapture.sh: bug fix

allsky.sh, config_repo/config.sh.repo, config_repo/ftp-settings.sh.repo, scripts/copy_notification_image.sh, scripts/endOfNight.sh, scripts/filename.sh, scripts/generateForDay.sh, scripts/removeBadImages.sh, scripts/saveImage.sh, scripts/timelapse.sh, scripts/upload.sh
Remove checks for CAMERA=auto.
Remove checks for obsolete variable names.
Merge functionality of scripts/filename.sh into config/config.sh (almost every script that sources in config.sh also sourced in filename.sh).
=> Remove legacy, pre-0.8.3 code

config_repo/config.sh.repo
This goes along with PR 91 in allsky-portal which uses this variable to display fan speed data on the System page.
=> config.sh.repo: allow users to specify fan data

scripts/darkCapture.sh
Need to copy the dark frame to the original directory $CURRENT_IMAGE was in, otherwise it goes in the directory that allsky.sh was executed in (usually $ALLSKY_HOME).
=> darkCapture.sh: bug fix with dirname

src/capture_RPiHQ.cpp
Fix bug in exposure code.
Minor logging changes for clarification.
Changes remaining spaces to tabs.
=> Exposure bug fix

src/capture.cpp
* Fix bug in keeping track of the number of ASI_ERROR_TIMEOUTs.
* Centralize calling of check_max_errors() so it's only called from one place.
This required making the "maxErrors" variable global and adding forward definitions of a couple functions.
* Move code that displays the sensor temp in preparation of also displaying the supported camera mode (to be done via a separate PR).
=> capture.cpp: check_max_errors

src/keogram.cpp
Fixes #881
Adds -D option to Disable displaying the date without disabling the hour labels.
Fixes issues with not always displaying the date.
Warns if an hour label or the date can't be displayed due to lack of space.
Displays the date even if there is no data for hour 0.
Other misc. changes - see the commits.
=> Keogram.cpp misc changes

.github/workflows/ci_compile.yml
Bash/shellcheck takes less time and is independent from the other steps. Therefore, this step is now prioritised.
=> testing: change priority

scripts/postToMap.sh
The PR switches the unique ID from Mac Address to Machine ID.
This is to address the fact that in some cases, the RPi can have multiple interfaces enabled and there's a need to parse the output and select only one mac address. Furthermore, if the user switches from `wlan0` to `eth0`, they would have a different mac address.
The Machine ID documentation can be found here:  https://man7.org/linux/man-pages/man5/machine-id.5.html
=> Switched from mac address to machine id

scripts/timelapse.sh
Instead of outputting an "ln -s" line for each file (there could be thousands), just output one line saying how many files there were.  This makes it MUCH easier to see what any error messages were.
Also, hide the useless "deprecated..." message which only confused users and made them think it was an error (it wasn't).
=> Timelapse.sh do not save ln  s

scripts/upload.sh
* Add "--debug" option for when used from the command line.  It adds debug info to the lftp output.
* Renamed "unique_name" to "file_type" to better reflect what it is.
* Remove unneeded compatibility checks.
* cd into the remote directory to make subsequent commands shorter, making it easier to see what they do when debugging.
* If removing the old destination file fails, wait a few seconds and try again, in case it was in use.
* Improved error checking of lftp.
* Only write to the output file if there was output.  This saves a write to the SD card in the vast majority of cases.
=> upload.sh: fixes and enhancements

config_repo/config.sh.repo, scripts/endOfNight.sh
* Similar to NIGHTS_TO_KEEP, but for web files i /var/www/html/allsky.
* Renames NIGHTS_TO_KEEP to DAYS_TO_KEEP because it keeps/deletes a full day's worth of images, not just nighttime images.
=> WEB_DAYS_TO_KEEP

gui/lighttpd.conf
This will be used by the Allsky website when creating thumbnails which take a while, to avoid having the user look at a blank screen for several seconds.
=> lighttpd.conf: enable disabling buffer

scripts/makeChanges.sh
* Was using wrong variables in update_config_js() function.
* Improved "sed" strings.
* Put "&#x27" in separate variable; when it was part of next line, gvim's colors got hosed up.
* Inform user of what was update.
=> makeChanges.sh: fixes with apostrophy

scripts/copy_notification_image.sh, variables.sh
This PR introduces the concept of notification image expiration times, the default being 5 seconds.
If a notification was displayed in the last 5 seconds a new one is to be displayed, don't display it.
For example, if we just displayed "Restarting Allsky" then don't display a "Allsky is starting up" notification because the user likely won't see the "Restarting Allsky" message.
This PR also keeps a log of the notification images displayed.  A future PR will have allsky.sh truncate the log so it only lasts through the current Allsky session.  This will be more important in the future when the capture programs can be sent a signal to re-read the settings, since that will be done in the same session.
This PR also allows a program calling copy_notification_images.sh to pass in argument to …
=> copy_notification_images.sh: expire time

src/capture_RPiHQ.cpp, src/mode_RPiHQ_mean.cpp
* Implement "--expires" to copy_notification_image.sh to force some notification messages to stay for a while.
* Standardize the output precision of MEAN to match what's displayed on the image, to make it easier to associate a log entry with an image.
=> capture_RPiHQ.cpp misc changes

scripts/upload.sh
Only allow one upload of a given file type at a time, to avoid multiple ones overwriting the same file and/or leaving temporary files on the server.
=> Upload one at a time

.gitignore, documentation/README.md
A location to store documentation and images that are linked into the Allsky README.md file, the Wiki, and Discussions.
Putting the files here eliminates the need to store them in an individual's personal website.
Ideally the "Documentation" directory would NOT be copied to a user's Pi when they grabbed the Allsky package.
=> Documentation

scripts/postToMap.sh
* Make sure Website URL and Image URL start with "http:" or "https:".  Two testers didn't do this, and it breaks the link on the map.
**Please check this on your Pi.  I have not tested it since I don't currently have access to my Pi. **
Simply copy the script to the Pi, then in the WebUI, prepend an "x" to your Website URL and Image URL and save the changes.  You should see two error messages at the top of the page.  Then remove the "x" and save the changes.  It should work.
=> postToMap.sh checks

gui/lighttpd.conf
When "mod_compress" was commented out in October 2021, the two lines in the file that use the "compress" module should have also been commented out.  Not doing so creates a couple entries in the error log.
=> lighttpd.conf: don't use compress modules

src/allsky_common.cpp, src/capture.cpp, src/capture_RPiHQ.cpp, src/include/allsky_common.h, src/include/mode_RPiHQ_mean.h, src/mode_RPiHQ_mean.cpp
Allow ZWO cameras to call get_focus_metric() so they can display the focus metric like RPiHQ cameras do.
This required moving the function to allsky_common.cpp and moving forward definition of it to allsky_common.h.
=> Focus metric

src/capture.cpp, src/capture_RPiHQ.cpp
SIGHUP is used to tell the capture programs to restart (eventually they will re-read configuration variables instead of actually restarting).
The prior Log() message when SIGHUP was received was temporary; this PR produces a better message.
=> Better msg about restarting

src/capture.cpp
* When switching from night to day, make sure the first exposure isn't longer than the user-specified maximum value.
* Also split a formula into pieces to allow values to be used in Log() statement, for better debugging.
=> capture.cpp: check for invalid exposure

src/allsky_common.cpp
We're using the exit code, not what it writes to stdout.
=> allsky_common.cpp: ignore sunwait output

scripts/postToMap.sh
* On the 8th or 9th of the month the check for day to upload fails since "date +%d" on the 8th of the month 8 returns "08".  When doing arithmetic, the shell treats a number that starts with "0" as octal and 08 and 09 are invalid octal numbers.  I had the exact same issue with the dark subtract script and wasn't able to find a good way around it.  Using "date +%e" returns "8" which is fine in shell arithmetic
=> postToMap.sh: fix bug with %d versus %e

scripts/saveImage.sh
* Perform sanity checks on crop settings: the crop area must fit on the image, the crop width and height must be even numbers, and the offsets must be numbers.
* While I was at it, I also performed checks on IMG_WIDTH and IMG_HEIGHT.
* We should probably perform checks in ALL scripts that a variable is a number when it's expected to be one...
=> Crop sanity checks

scripts/upload.sh
systemctl sends SIGTERM to terminate a service, but doesn't send any signal to start it.  A "restart" is actually "stop" (SIGTERM) followed by a "start".
=> upload.sh: remove incorrect code

src/capture.cpp, src/capture_RPiHQ.cpp, src/include/allsky_common.h
* Centralize all #defines to top of capture*.cpp files.
* Moved #defines that were common between capture.cpp and capture_RPiHQ.cpp to allsky_common.h.
* For RPiHQ the command-line variables now have centralized defaults, rather than hard-coding where the variable is defined.
=> Centralize #defines

allsky.sh
If a user's Pi doesn't have the `libcamera-still` command, allsky.sh currently assumes `raspistill `exists, and the capture_RPiHQ command will start, only to produce an error every time it tries to take a picture.
This PR checks the the existence of `raspistill` and produces a non-recoverable error if it doesn't exist (and `libcamera-still` doesn't either).
=> allsky.sh: check for missing RPiHQ software

website/install.sh
* The thumbnail directories will NEVER exist since we rename the old "allsky" directory and create a new one that doesn't have those directories.
* Do more intelligent move of prior images and videos.
=> install.sh: Always make thumbnail directories

scripts/copy_notification_image.sh
* Check if daytime images are being taken, in addition to them being saved (it's possible $DAYTIME_SAVE can be "true" but $DAYTIME_CAPTURE is false).
* Check for $IMG_UPLOAD, not the incorrectly named $UPLOAD_IMG.  This bug causes notification images to NOT be uploaded, so things like "Camera is off during day" don't appear when they should.
=> copy_notification_image.sh: fix 2 bugs

config_repo/config.sh.repo
=> config.sh.repo: remove compatibility checks

src/capture.cpp
* Output the red and blue balance even when not in auto white  balance.
=> capture.cpp: output red and blue balance

src/capture_RPiHQ.cpp
Manual exposures don't need a delay since the user specifies the exposure time, so the software doesn't have to do multiple captures to get the best exposure.
=> capture_RPiHQ.cpp: decrease manual exposure delay

src/capture.cpp, src/capture_RPiHQ.cpp
It's a bool so shouldn't really be compared to 1.
=> Fix daytimeCapture

src/capture.cpp
* Display camera bit depth and whether or not it's a "trigger" camera.  This is FYI only.
OTHER MINOR CHANGES:
* Change word to lowercase to be consistent with other messages. Remove a space in list to line up better.
* Added "C" to sensor temperature to be clear about units.
* Only display video modes supported if it's a "trigger" camera, since non-trigger cameras have only one mode ("NORMAL").
=> capture.cpp: support 2 more camera variables

README.md, allsky.sh, config_repo/allsky.service.repo, src/capture.cpp, variables.sh
This exit code is thrown when the camera can't be found.  A notification message is displayed and the service is stopped.
=> Support EXIT_NO_CAMERA

README.md, config_repo/ftp-settings.sh.repo, scripts/upload.sh
Add support for using `scp` to upload images to a remote server. Requires use of SSH key authentication.
Support for username/password authentication in `scp` could be added in the future if needed.
In `allsky` client (Raspberry Pi 4 host):
```
~/allsky/scripts $ ./upload.sh /tmp/test.txt allsky-website/images test.txt
upload.sh: Copying /tmp/test.txt to hectorramos.com:allsky-website/images/test.txt
test.txt                                      100%    0     0.0KB/s   00:00    
```
In remote server (allsky-website host):
```
~/allsky-website/images$ ls
image.jpg  test.txt
```
=> Add support for scp protocol in uploads

src/ASI_functions.cpp, src/Makefile, src/capture.cpp, src/capture_RPiHQ.cpp
Every camera model has different values for minimum, maximum, and default for various capabilities, like brightness and gain.  In order for the WebUI to be able to display the correct values, they need to be obtained and saved to a file.  This PR does that.
Because the Raspberry Pi cameras cannot be queried like the ZWO ones can, a hard-coded table is built that contains those capabilities and their values, for both raspistill and libcamera.  Currently only the RPi HQ camera is supported, but a placeholder for the Arducam 64 megapixel camera was added.
=> Get and save camera capabilities

scripts/generateForDay.sh
* The thumbnail file that stays in allsky/images/DATE should be called `thumbnail-DATE.jpg` so it's not confused with the video file by the WebUI (which doesn't check the extension).
* Display a message if the thumbnail file isn't created.
* Before uploading the thumbnail, make sure it exists.
=> generateForDay.sh: add checks, rename thumbnail

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
Users are bypassing the Issue Template which asks them to use the Discussions link for questions, and are entering questions as Issues.  This PR should force them to use the template, which was my intention all along.
This PR also adds details to the Issue Template so we (hopefully) get more information.
=> Force users to use issue template

.github/ISSUE_TEMPLATE/bug_report.md
When the user enters a new Issue, they are in "Edit file" mode so won't see bold, code blocks, etc., so remove them from the text.  This makes the text easier to read.
Leave
=> bug_report.md: Remove most markdown

scripts/postToMap.sh
${W} contains warning messages, but is being overwritten by the website URL's domain.
=> postToMap.sh: fix bug with $W

scripts/upload.sh
If multiple lftp's are going one for different file types, it's likely the LFTP_CMDS file will get overwritten and the wrong file will be uploaded.
=> upload.sh: use unique command files

allsky.sh, scripts/upload.sh, variables.sh
Keep track of the number of aborted uploads due to another one in progress.  This can give the user an indication of whether or not they should decrease the frequency of uploading files, e.g., every other one.
=> ALLSKY_ABORTEDUPLOADS

scripts/postToMap.sh
When running via endOfNight.sh, output goes to the log file which doesn't handle color, so turn off colors.
=> postToMap.sh: don't use colors at endofnight

scripts/upload.sh
The code to retry an "rm" was missing a single quote, so the 2nd "mv" gave a usage message and the temporary file stuck around.
=> upload.sh: remove temporary file fix

src/allsky_common.cpp
Don't output message about no save directory when CC_saveDir is set. since we'll be saving camera info and exiting.
=> allsky_common.cpp: bug fix

scripts/endOfNight.sh
* Determining what directory to look for images by using today's date - 12 hours only works if endOfNight.sh is called within 12 hours of the night-to-day transition, which it normally is.  However, if a user calls it manually they may call it late in the evening, for example, which might be 14 hours after the transition.  In this case, endOfNight.sh will use the current day's directory, which is still being written to.
=> endOfNight.sh: check for 'yesterday'

src/ASI_functions.cpp, src/allsky_common.cpp, src/capture_RPi.cpp, src/capture_ZWO.cpp, src/include/allsky_common.h
The invoker now specifies the FILE to save camera capabilities to, rather than the DIRECTORY.  This means a generic file name can be used so other scripts reading the file don't need to know the CAMERA_TYPE and CAMERA_MODEL, which are specified in the file, resulting in a catch-22.
=> Use CC_saveFile

config_repo/configuration.json.repo
For consistency, the website should display the latitude and longitude with N, S, E, and W, regardless of what's entered into the configuration file.  s_latitude and s_longitude display the "s"tring version of them, i.e., with N, S, E, W.
=> configuration.json.repo: prepend "s_"

html/includes/functions.php, html/index.php
The variables are only needed by index.php, so it calls the new function to initialize them.
Other .php files that don't need those variables don't initialize them, which saves reading a couple files.
=> Call a function to initialize variables

website/install.sh
In order for the login running website/install.sh to be able to chmod pi:www-data, it needs to either be in the "www-data" group, or run as sudo.  Apparently it's not in that group on some machines, so use "sudo".
=> install.sh: use sudo chown

config_repo/configuration.json.repo
Add settings to allow user to change the following items on the constellation overlay:
* Default font size.
* Whether or not cardinal points are displayed.
* Font size of cardinal points, to make them easier to see.
* Colors of any of the items on the overlay.
=> configuration.json.repo: add settings

html/index.php
On Buster, "/javascript" was a lighttpd alias to /usr/share/javascript.  That doesn't exist on Bullseye (at least the light version), so use a different jQuery.
=> index.php: Use different jquery

src/ASI_functions.cpp
More testing will be needed to see if ZWO and RPI can handle no delay.
=> ASI_functions.cpp: set min_delay to 0 ms

src/ASI_functions.cpp, src/allsky_common.cpp, src/capture_RPi.cpp, src/include/mode_mean.h, src/mode_mean.cpp
* Changed exposure-related variables to _us longs rather than some double, some _s, and some _us.  It was too confusing.
* Also added/changed comments and Log() messages.
**TODO: fix algorithm where the gain goes to max value before exposure changes.**
=> Simplify arguments to aegGetNextExposureSettings()

config_repo/allskyDefines.inc.repo, html/includes/functions.php, install.sh
Move the  define() statements out of includes/functions.php into a new "allskyDefines.inc" file that is created during installation based on the .repo version.  This makes maintenance a little easier.
=> Web UI use 'allskyDefines.inc'

src/capture_RPi.cpp, src/include/mode_mean.h, src/mode_mean.cpp
The RPi-specific "quickstart" did the same thing as the generic "SkipFrames", but SkipFrames is configurable by users for day and night, and "quickstart" wasn't.  Further, "quickstart" saved the images then slept a second, messing up the timelapse.
=> Remove quickstart, use skip frames instead

src/ASI_functions.cpp
* Bug fix: supported image formats had the value and label backwards.
* All settings with an array should have "value" and "label" sub-fields.
=> ASI_functions.cpp: bug fixes and standardization

config_repo/options.json.repo
ZWO camera's don't support rotation, so need the "display" placeholder to be "rotation_display".
=> options.json.repo: use "rotation_display"

scripts/makeChanges.sh
* The user shouldn't see the "XX_WORKED_XX" message - it's for internal use only.
* Split a long line into separate line to make it easier to read.
=> makeChanges.sh: cosmetic changes

html/includes/functions.php
* The settings file has already been read so might as well get the temptype so the system.php file doesn't have to re-read the file.
* Check that $_POST['csrf_token'] is set before using it.
* Settings file is a generic name so don't need the $camtype to determine the name.
=> functions.php: global $temptype, others

src/allsky_common.cpp
=> allsky_common.cpp: ignore cameramodel

config_repo/config.sh.repo
* During installation, if the settings file isn't found we get several confusing error messages from the settings() function.  Checking for existence of the file first allows us to produce a useful error message.
* To be consistent with other scripts, renamed the variable from CAMERA_SETTINGS to SETTINGS_FILE since it has more than just camera settings.
=> config.sh.repo: exit if settings file not found

install.sh
After installing Allsky with no prior installation, the first time they go to the WebUI it won't find an image to display, so create one that tells them to configure Allsky.
=> install.sh: give 'em something to look at

variables.sh
So scripts that do a `source variables.sh || exit 1` work
=> variables.sh: return 0 on success

scripts/postToMap.sh
Plus, the way Thomas implemented the server, "allskyversion" is all lower-case.
=> bug fix: add missing comma

html/includes/camera_settings.php
It wasn't displaying "widetext" fields correctly when not showing advanced options
=> camera_settings.php: "advanced" bug fix

src/capture_RPi.cpp
Seeing LIBCAMERA_LOG_LEVELS=ERROR,FATAL in the log output confuses users, so don't include it.  However, it still needs to be in "cmd".
=> capture_RPi.cpp: Log() of cmd

src/mode_mean.cpp
The old single multiplier of 2 * mean_threshold could result in "slow forward" when the mean was pretty far away from the target, e.g., mean == 0 and target == 0.2.  Therefore, lower the multiplier and add a second one with an even lower multiplier that increases the ExposureChange less.
Also, use the difference is the actual mean and the target mean, not the forecasted or expected new mean (which aren't always accurate).
=> mode_mean.cpp: change multipliers

scripts/copy_notification_image.sh
All notification images should go to the remote website as well as the local one, if they exist.
=> copy_notification_image.sh: copy to WEB_IMAGE_DIR

html/dist/css/custom.css, html/includes/functions.php, install.sh
If a user accidently removes the contents of the `allsky/html` directory (like I did), they can grab it from GitHub, but need to run the installation script to create `allsky/html/includes/allskyDefines.inc`
=> Allow recreating allskyDefines.inc

scripts/postData.sh
If a file to be uploaded isn't found (usually because it's null), output a string representation of the file.
=> postData.sh: add debugging info

scripts/makeChanges.sh
determineCommandToUse() sends error output to stdout, so we need to display it if there's an error.
=> makeChanges.sh: add error output

scripts/updateWebsiteConfig.sh, website/install.sh
When called via the WebUI, we just want a "configuration file was update" message rather than a separate message for every field that was update, which no other updates do.
=> Allow multiple levels of verbosity in update website config.sh

html/dist/css/custom.css
* With a narrower left sidebar, we need to have the menu appear when the right side is larger. Unfortunately, since 768px was hard coded into a couple other third-party .css files and I didn't want to change them, it required adding several lines to this file.  If you know of a better way, please improve.
* Narrow the margin on the right pane prior to having the menu appear.
* NOTE: This still looks terrible on a mobile device - the lines in the table appear to have a minimum size so go past the table behind it.  I'm not sure why.
* .info-item wasn't used so delete it.
=> custom.css: improve UI on small devices

config_repo/sudoers.repo, html/includes/save_file.php
If a user updates a remote file in the WebUI at the same time Allsky is uploading a file, the WebUI action won't work since the upload pid fix exists and isn't writeable by the web server.
This fix makes the WebUI run the "upload.sh" file as pi.
=> Execute upload.sh as pi

scripts/upload.sh
Put all the "lftp" log files in a separate directory so the tmp directory isn't so cluttered.
=> upload.sh: put log files in separate directory

config_repo/Makefile
Force a "udevadm trigger" when AllSky is first installed. This is to ensure that the asi rules are recognised by AllSky as the ZWO capture routine is required to run as part of the installation. 
Without this the user will get permission errors when AllSky attempts to get the camera configuration
=> Fix for udev permissions on installation

documentation/index.html
When viewing the GitHub page, the shortcut icon isn't downloaded.  See if removing the "type=" attribute fixes this.
=> index.html: test with no type for icon

documentation/documentation.js
Trying to determine why links to files in current directory don't work when the directory is "documentation".
=> documentation.js: add debugging stmts

documentation/css/documentation.css
* Add extra space between <detail> sections so it clearer where one ends and the next one begins.
* Move a rule to be next to a related one.
* Remove commented-out rule.
=> documentation.css: put space between sections

install.sh
The user that installs Allsky needs to be in the "www-data" and "sudo" groups.  Add them if needed.
=> install.sh: put user in correct groups

config_repo/options.json.repo
Don't call it "external" which isn't meaningful to users.
=> options.json.repo: rename the overlay method

config_repo/config.sh.repo, install.sh
Only needed for "old" style prior Allsky, and only if we can find the old settings file.
Doing this will allow Allsky to start after the reboot.
=> Restore lat and long

install.sh
The file doesn't exist yet, and is source'd after it's created
=> install.sh: remove unneeded source of config.sh

html/includes/functions.php
Turns out, displaying the default for empty values isn't good.  The settings file may have "" but the user sees the default.  The Allsky Settings page should always display what's in (or not in) the settings file.  Will do a different PR to not allow blank settings if they are required.
=> functions.php: fix

config_repo/options.json.repo, html/includes/createAllskyOptions.php
This is the beginning of the capability to have the WebUI check for required fields that are empty.  Since most fields are required, an "optional: true" field is added.  If the "optional" field is missing then "false" is assumed.  In theory, all the required fields could have "optional: false", but that just clutters things.
The majority of the work will be done in allskySettings.php via a separate PR.
=> Indicate optional settings

scripts/postData.sh
We already checked for the existence of a local website configuration file and set a variable, so use the variable instead of checking the file twice. Also split a long [[ ]] && statement so it's easier to read.
=> postData.sh: don't check for file twice

.github/workflows/ci_compile.yml
And treat all .sh files the same except variables.sh which sets a bunch of variables but doesn't use them.
=> ci_compile.yml: do less checking

html/documentation/css/custom.css
The Setting names were almost impossible to see in dark mode - they were dark gray against very dark gray. Also, get rid of transition on Yes/No labels - they were annoying.
=> custom.css: fix color of dark text

html/documentation/css/custom.css
These entries override what's in viewer.css which comes AFTER custom.css, so we need the !important's
=> custom.css: improve image viewer

html/includes/functions.php
This gets rid of matching on strings contained in comments, and allows variables to be indented.
=> functions.php: change patter match, add comments

src/allsky_common.cpp
instead of older "externaloverlay" name
=> allsky_common.cpp: use "overlaymethod"

config_repo/options.json.repo, scripts/makeChanges.sh
If the user changes the "Display Settings" setting in the WebUI but there isn't a local or remote Website, display a warning message.  If they change a setting used by both the Allsky Map and a Website and there isn't a website, don't display the warning.
=> Fix display settings error message

scripts/upload.sh
Not all FTP servers support the PWD command, so uploads to them fail. Execute "cd ." if the PWD fails.  This assumes that all servers support one or the other.
=> upload.sh: not all servers support PWD

config_repo/config.sh.repo, config_repo/ftp-settings.sh.repo
Add version numbers to the files so we know if we can simply copy prior config files to new releases.
=> Add versions to config.sh and ftp settings.sh

config_repo/allsky.rsyslog.repo, config_repo/allsky.service.repo, config_repo/allskyperiodic.service.repo
Modified the services and rsyslog config to write to specific log files. This will prevent the AllSky log message sbeing duplicated in syslog and messages.
Log rotation has remained the same
=> Change allsky logging to ensure logs only written to allsky log files

src/ASI_functions.cpp, src/include/allsky_common.h
Fix to return a cameraNumber thats an index into the array of control values for the camera.  It used to always return an index into the 1st entry in the array.
=> Fixes to support more RPi cameras

html/index.php
The $config for the remote Website overwrites $config used to set global variables.
=> WebUI bug fix: $config overwrites prior $config

src/allsky_common.cpp
"extra" was the old name; it's now "extraargs"
=> allsky_common.cpp: fix typo

scripts/periodic.sh
This causes the service to exit gracefully rather than with 130 (128 + SIGINT (2)) or 143 (128 + SIGTERM (15)).
=> periodic.sh: exit 0 when signal is sent

src/ASI_functions.cpp, src/allsky_common.cpp, src/capture_RPi.cpp, src/include/allsky_common.h
If the user either didn't specify an argument, or specified the default, don't pass that argument to the libcamera-still or raspistill commands.  Passing them doesn't do anything other than increase the length of the command line.
=> Pass only non-default arguments

src/allsky_common.cpp
* Need to check specified debug level, not CG.debugLevel when determining if we should create a System Message.
* Remove any trailing \n.
=> allsky_common.cpp: bug fix with debugLevel

scripts/makeChanges.sh
When changing the camera type we need to stop Allsky first or else we're likely to call the capture program while it's already running, causing an error.
=> makeChanges.sh: stop Allsky if needed

scripts/functions.sh, src/ASI_functions.cpp
If a user tried changing the camera type while Allsky was running it could have tried running the libcamera-still command while one was already running which caused a problem.  (I think) calling capture_ZWO when one was already running would also cause a problem.
This PR fixes the bug by stopping Allsky before changing the camera type.
=> Bug fix ASI_EXPOSURE failed

install.sh
Not sure what causes the usage messages; most likely ${LOCALES} is incorrect.
=> install.sh: check for whiptail usage message

allsky.sh
It's no longer needed now that config.sh has a version number.
=> allsky.sh: remove compatibility check

html/includes/status_messages.php
When in "escape" mode, can't output any single quotes - need to convert all of them to &apos;
=> status_messages.php: bug fix with single quotes

install.sh
A command like:
MSG="some message" ${LOCALES}
sets $MSG then calls ${LOCALES} which is invalid.
Need to remove the space between them.
=> install.sh: bug fix with space

install.sh
If the Pi is already called "allsky" then set the NEW_HOST_NAME to that, so the "You can access the Pi..." message is correct.
=> install.sh: set NEW_HOST_NAME

src/capture_RPi.cpp
For binning, don't hard-code the HQ camera's width and height since we now support other cameras with different values.
=> capture_RPi.cpp: bug fix with width and height

scripts/check_allsky.sh
When determining if an image size is "too large" and may cause a problem with timelapse video creation, use CROP_IMAGE, IMG_RESIZE, and the WebUI size (in that order), THEN use the sensor size if none of the others are set.  This should give us the actual size of the image.
=> check_allsky.sh: more intelligent image check

install.sh
Some files within ${ALLSKY_CONFIG} may have been created by the WebUI or a module, both of which run as www-data, so "pi" may not be able to chmod them.  Run those commands with sudo.
=> install.sh: use sudo with chmod

scripts/addMessage.sh
If an entry is corrupted, e.g., the message has some non-printable characters, then don't try to update COUNT.
=> addMessage.sh: handle corrupted entries

scripts/addMessage.sh
When messages have a "*" in them, it throws off the grep and sed regular expression, so we need to escape the "*"'s. Also add a "tail -1" so we only grab the last matching entry, in case the file gets corrupted and there are multiple identical entries.
=> addMessage.sh: handle "*" in messages

install.sh
"C.UTF-8" and "POSIX" are valid locales, although I suspect not many people use them. "C.UTF-8" is similar to "en_US" but with more structure.
=> install.sh: Allow all valid locales

scripts/timelapse.sh
If a mini timelapse is running at the same time as a full timelapse (which is very possible), whichever runs first will remove the $SEQUENCE_DIR directory, and because both invocations of timelapse.sh use the same directory name, the other invocation will no longer be able to find the files. This PR gives the directory a unique name by appending the timelapse.sh process ID to the name.
=> timelapse.sh: use unique SEQUENCE_DIR names

src/ASI_functions.cpp, src/allsky_common.cpp, src/capture_RPi.cpp, src/capture_ZWO.cpp, src/include/allsky_common.h
Using an RPi camera that wasn't an HQ one didn't work - it said it couldn't find the camera.  It worked at one time, but when I added the code to support multiple ZWO cameras connected at once, I broke the RPi code.
This PR fixes this bug and allows multiple RPi cameras to be connected as well (although I'm not sure if that's physically possible).
=> capture_RPi fix bug with non-HQ cameras

allsky.sh, config_repo/options.json.repo, html/includes/allskySettings.php, html/includes/createAllskyOptions.php, html/includes/functions.php, scripts/makeChanges.sh
It's possible to have multiple ZWO cameras attached to the Pi at once (not sure about RPi).
This PR allows the user to specify which camera to use via a new "Camera Number" setting in the WebUI.
This works well, but switching cameras in the WebUI needs more testing, so the "Camera Number" field is hidden in this release.
=> Support multiple cameras attached to Pi

html/includes/system.php
Say "Allsky started" rather than "allsky service started" which is technically correct but users won't necessarily know what a "service" is.
=> system.php: Use "Allsky", not "allsky"

src/capture_RPi.cpp
it's more efficient than "pgrep | xargs kill"
=> capture_RPi.cpp: use pkill

html/includes/createAllskyOptions.php
createAllskyOptions.php sometimes doesn't see a camera-specific settings file, so it creates a new, generic one.  This PR should provide additional info.
=> createAllskyOptions.php: add debugging statements

html/includes/overlayutil.php
If a field has one or more newlines, the field will be split into multiple lines: one with everything up to the newline, and the others with everything after the newlines. If any subsequent lines don't have a space, $fieldSplit[1] won't exist and a PHP error will be thrown.
Note the TODO in the comments.
=> overlayutil.php: Check for only 1 field

scripts/functions.sh
When calling "display_msg() --log" we don't want escape characters for colors in the log file - it makes it hard to read.
=> functions.sh: log msg without esc chars

scripts/modules/allsky_overlay.py
Allsky accepts lat and lon in  N, S, E, W format as well as float. This PR fixes allsky_overlay.py to accept both as well.
Please see the TODO comment.
=> allsky_overlay.py

html/cgi-bin/format.py, html/includes/moduleutil.php, scripts/modules/allsky_overlay.py
- Adds ?? as a default for an invalid variable format
- Allows the ?? to be changed in the overlay config
- Fixed 'Display Sample Data' not returning anything when there is an invalid format
- Allowed new settings to be added to modules without having to remove and readd the module in the module manager
=> Updates for variable formats

install.sh
- Checks if modules are in /etc/allsky and if so move them to the new location /opt/allsky
- If the pistatus or pigps modules exist in /opt/allsky/modules then delete them as they are now part of core allsky
=> Temp code to move modules that have changed location  during development

install.sh
Display a message when adding the user to the www-data group.  This is primarily for troubleshooting since it appeared to either not happen or not work with one user during installation.
=> Install.sh display msg with addgroup

install.sh
The web server couldn't write to the log file since it was owned by root and grouped to pi, mode 664. That caused the web server to not start.
=> install.sh: fix permissions on error.log

config_repo/options.json.repo
It's now set during installation if needed, and passed to capture programs via allsky.sh. If this works, the whole "locale" block should be removed and the "locale" setting should be removed.
=> options.json.repo: hide locale

html/css/overlay.css
Make it higher to fit Bool, Date, and Number without scrolling.
=> overlay.css: increase height of scrollBody

scripts/endOfNight.sh
Bug fix: if the allsky/images directory had directories with names that started with "20" but weren't all numeric, the (( )) check could fail.
This PR only checks directories that have format YYYYMMDD.
=> endOfNight.sh fix with directory name

scripts/generateForDay.sh
Use bash string substitution to remove double quotes, rather than "tr".
=> generateForDay.sh: use shell substitution

install.sh
"whiptail --menu" requires groups of 2 arguments - a tag and item/description. In our case, the tag and description are the same string so this PR basically presents whiptail with an array of ' tag "" ' strings.
=> install.sh: display single row in --menu

scripts/upload.sh
If there are "a lot" of aborted uploads, let the user know.
=> upload.sh: add System Message on aborts

scripts/addMessage.sh
We were using "/" for the regex search, but "/" could (and often was) in messages so the sed failed. Use "%" instead (which is not likely to be in a message), but convert it to its ASCII code in the message.
=> addMessage.sh: bug fix with sed

install.sh
* Use "vcgencmd get_config total_mem" if possible to get the actual memory on the Pi.  It's very accurate.
* Set DESIRED_COMBINATION to the amount of physical memory+swap and check against that in a loop.  This will be easier to maintain.
* Handle no swap correctly (0 versus 1 MB).
* Handle user not removing leading "0" in suggested swap size.
* Increase max swap if needed.
=> install.sh: improved swap handling

scripts/check_allsky.sh
Depending on what image delay and mini timelapse settings a user has, as well as how fast their Pi is, it's very possible a mini timelapse creation will start before the prior one finishes.  Try to detect that possibility.
=> check_allsky.sh: add checks for mini timelapse

config_repo/overlay/config/overlay-RPi.json, config_repo/overlay/config/overlay-ZWO.json, config_repo/overlay/config/overlay.json
In the repo `overlay*.json` files:
* Merge the DATE and TIME fields since users typically want both of them, and it's easier to deal with as one field.
* Add CAMERA_TYPE and CAMERA_MODEL to the bottom left of the image.
* Remove TEMPERATURE_C from RPi version.
* Set the fall-back "overlay.json" file to be the ZWO version without TEMPERATURE_C.
=> Overlay.json updates

variables.sh
Putting in ALLSKY_TMP doesn't work during installation since it clears out that directory.
=> variables.sh: change location

scripts/flow-runner.py, scripts/flowupgrade.py
* /opt/allsky is now ALLSKY_MODULE_LOCATION in variables.sh, so use it instead of hard-coding the paths in the .py files.
* Use ALLSKY_SCRIPTS instead of ALLSKY_HOME/scripts.
* Centralized checking for variables - code was in two places.
=> Use new variables

scripts/upload.sh
* Minor bug fix: add missing "$".
* Don't output our own error message if "cd" fails since lftp outputs a message.
=> upload.sh: minor bug fix

website/install.sh
* Should exit if upload_data_json_file () fails.
* Only call does_prior_Allsky_Website_exist() for local installations.
=> install.sh: couple bug fixes

html/includes/functions.php, html/index.php
Fix bug whereby if the remote_configuration.json file wasn't valid the WebUI would fail to display.
=> Web UI don't exit if unable to read remote website config

html/js/overlay/oe-uimanager.js
This is caused by the html canvas having the same height as the raw image but drawing on the stage is done using scaling on x and y.
The fix is not ideal and this will need looking at again
=> Fix to remove large black block under the overlay editor 

scripts/saveImage.sh
When cropping, stretching, or resizing an image, make the log entry's format consistent:   *** ${ME}: some_message
=> Update saveImage.sh: use consistent log entry formats

scripts/check_allsky.sh
For whatever reason, a tilda at the start of a file/directory name wasn't working so the item wasn't found. Replace tilda with $HOME so it works.
=> check_allsky.sh: handle tilda

install.sh
Error message needs to go to stdout so $VALUE can be set correctly.
=> install.sh: bug fix: write error to stdout

config_repo/options.json.repo
If a user set their settings back to defaults then there was no way to set the locale since it wasn't displayed.
=> options.json.repo: display locale

scripts/upload.sh
Fixes image uploads to S3 when using `IMG_UPLOAD_ORIGINAL_NAME="false"` in config.sh. (Images are uploaded with date/time in the name when they shouldn't).
See https://github.com/thomasjacquin/allsky/discussions/1193#discussioncomment-5959444
=> Add ${DESTINATION_NAME} to s3 upload target

scripts/removeBadImages.sh
* Convert all comparisons of LOW and HIGH to use "bc".  Previously we compared "HIGH -gt 100" but if HIGH was 100.0 it failed.
* Remove a couple unneeded comments.
=> removeBadImages.sh: bug fix with decimal HIGH

src/allsky_common.cpp, src/capture_ZWO.cpp, src/include/allsky_common.h
This fixes a likely bug that can cause "ping pong" messages.
It also provides more log information to help debug a problem Jim has where at night, the MEAN brightness goes near 255 and stays there.
=> capture_ZWO changes to gather more info

html/js/overlay/oe-uimanager.js
Set the limits of the spinners in the text properties for x and y based upon the image size
=> Auto set the spinner limits in the text properties editor

html/includes/allskySettings.php, html/includes/functions.php
When error messages include the command executed as well as it's error output, that looks ugly from a user's perspective.  They don't know what the command is.  This is especially true with makeChanges.sh, so don't show the command executed.
=> Allsky settings optionally don't add to error message

html/js/overlay/oe-uimanager.js
- When an image is moved out of bounds using the spinners the image is outlined in red the same as when moving using drag and drop
- Changed image spinners so that the max value is set to the image size
=> Fix for out of bounds images when using spinners - addresses #2621

html/index.php
The recent merge for keeping the save buttons at the top of the page is not checking that the button exists. On pages that dont have the buttons Javascript errors are being thrown as the page scrolls.
Changed the code to only add the stick logic on the settings page
=> Fix js errors thrown on pages other than settings cased by https://github.com/thomasjacquin/allsky/pull/2666

html/documentation/explanations/SystemPageAdditions.html, html/documentation/miscellaneous/AllskyMap.html, html/documentation/settings/allsky.html, html/documentation/settings/allskyWebsite.html
Use    `external="true"` instead of hard-coding the "external" web page symbol.  This makes it easier to globally change if needed.
=> Use 'external' attribute in documentation

scripts/installUpgradeFunctions.sh, variables.sh
Many scripts use ${DEBUG} to enable debugging, so don't use it as a color name.
=> Don't use "DEBUG" for color   use "cDEBUG"

allsky.sh, html/documentation/changeLog.html, scripts/functions.sh
At startup, check if the settings.json file is properly linked to its camera-specific file.
Some users have reported it's NOT linked - not sure if they manually edited the file or there's a bug somewhere.
=> Determine if settings.json is linked properly

scripts/check_allsky.sh
Want to eventually put all checks in functions so the main body is very simple to read.
=> check_allsky.sh: add couple functions used for checking things

html/documentation/explanations/SSL.html
Instead of telling users to follow instructions on a different page, include those instructions in Allsky.
This resolves Discussion #2706
=> Vastly improved instructions for installing SSL

install.sh
The Allsky documentation tells people to create that directory for their SSL certificates so Allsky can carry them forward.
=> Restore any prior config/ssl directory

install.sh
Improve many of the log messages to make troubleshooting easier.
=> Improved log messages in install.sh

install.sh
Using "mv" to replace a file removes any hard links it has, so use "cp" instead.
=> Fix install.sh bug when updating settings file

allsky.sh, scripts/flow-runner.py, scripts/modules/allsky_shared.py, variables.sh
- Allow the number of images to process to optionally be passed as an argument (to flow_runner.py ?). The default can remain at 10.
>Added --flowtimerframes option to flow-runney.py Default is 10
- Add a variable to allsky/variables.sh to define the directory, e.g., ALLSKY_FLOWTIMINGS. This will make it easy for check_allsky.sh to find the directory.
>Added the following variables
>ALLSKY_FLOWTIMINGS="${ALLSKY_TMP}/flowtimings"
>ALLSKY_FLOWTIMINGS_DAY="${ALLSKY_FLOWTIMINGS}/day-average"
>ALLSKY_FLOWTIMINGS_NIGHT="${ALLSKY_FLOWTIMINGS}/night-average"
- How will check_allsky.sh know the names of the files? Should other variables be added, e.g., ALLSKY_FLOWTIMINGS_XXX ?
> See above
- allsky/allsky.sh should rm -fr "${ALLSKY_FLOWTIMINGS}" so we know any files are from the current instance of …
=> Changes as requested on #2717

src/Makefile
=> src/Makefile: temporarily break dependency on patchsunwait

src/allsky_common.cpp
If the target mean is 0.0, the min/max would also result in 0.0, so don't need the checks.
=> allsky_common.cpp: remove unnecessary checks

src/ASI_functions.cpp, src/allsky_common.cpp, src/capture_ZWO.cpp, src/include/allsky_common.h
For capture_ZWO.cpp, set the defaults, then get the arguments, so the "help" message shows the defaults and the debug message show the argument values.
Should probably do this for capture_RPi.cpp as well.
=> Capture changes

html/documentation/changeLog.html, html/includes/dashboard_WLAN.php, html/index.php
If multiple WLAN interfaces are present, and are named "wlan0", "wlan1", etc., display information on each of them.  We stop when "wlanX" isn't found.
=> Allow multiple wlan interfaces

html/documentation/changeLog.html, html/documentation/css/custom.css, html/includes/allskySettings.php, html/includes/functions.php, html/includes/status_messages.php, html/index.php
If a user enters an invalid number, e.g., not [+-0-9,.] display an error message and don't update the settings file.
Also, if one of the settings that are used to determine the time between images display is invalid, also display an error message.
=> Check for valid numbers

scripts/functions.sh, scripts/saveImage.sh, scripts/timelapse.sh, scripts/upload.sh, variables.sh
This function ensures that only one instance of the calling process is running.  It replaces code in upload.sh and timelapse.sh.
=> Add one_instance() function

scripts/functions.sh
Also, use the full file name in error output.
=> check_settings_link(): use settings()

allsky.sh, scripts/darkCapture.sh, scripts/endOfNight.sh, scripts/functions.sh, scripts/generateForDay.sh, scripts/saveImage.sh, scripts/timelapse.sh, scripts/upload.sh, variables.sh
* Improve the way process locking is done and the aborted messages.
* The files listing the aborted processes are all in a sub-directory in allsky/tmp.
* Create a global make_thumbnail() function rather than using the one defined in a scripts/*.sh file.  More scripts will use this via another PR.
* Many other changes that aren't related to process locking, but hey, I was already editing the files...
=> Improvements to process locking

install.sh
* When a user exits the installation part way through, it should be able to skip the steps already performed.  This PR implements that ability.
* More work may be needed after additional testing.
=> Install.sh support restarting where left off

allsky.sh, html/includes/functions.php, install.sh
Additional changes to support restarting installation where the user left off.
=> Additional install.sh restart changes

scripts/functions.sh
Often the jq fails because FILE doesn't exist, and jq outputs that error so there's no need to do "ls" of the file since it will also fail.
=> functions.sh: Don't do "ls -l" of FILE

scripts/functions.sh
json arrays, e.g., "keys[]" can NOT start with a period, but other fields must.
=> settings() bug fix

scripts/removeBadImages.sh
The "X consecutive..." message doesn't quite fit in the screen so remove a newline.
=> removeBadImages.sh: shorten message so it fits in image

src/capture_RPi.cpp, src/include/mode_mean.h, src/mode_mean.cpp
Rename "mean_threshold" to "currentMean_threshold" to better reflect what it's for.
Move from mode_mean.h to allsky_common.h.
=> Rename and move "mean threshold"

src/capture_RPi.cpp, src/include/mode_mean.h, src/mode_mean.cpp
The "mean_p[012] variables moved from mode_mean.h to allsky_common.h.
=> Use mean_p[012] in allsky common.h

scripts/functions.sh
Most of the time the script that calls settings() doesn't care if the return is "" or "null" so return "" in either case, UNLESS "--null" is passed in. This makes the code that calls settings() a little cleaner.
=> Update functions.sh: implement --null

scripts/modules/allsky_overlay.py
Fixes for
1) Only process .json and .txt files when looking for extra data
2) Fix empty strokes on rotated text
=> Fixes for #2833

src/capture_RPi.cpp
This means the extra args will overwrite anything already on the command line.
=> Update capture_RPi.cpp: add extraargs to end of cmd line

scripts/timelapse.sh
This allows multiple different timelapse creations at once.
=> Update timelapse.sh: use unique names for sequence directories

src/capture_RPi.cpp
If we don't specify when they are the default then auto mode is enabled.
=> Update capture_RPi.cpp: Must specify red and blue in manual mode

html/includes/overlay.php, html/includes/overlayutil.php
- Prevent files on osx zip files from confusing the font uploader
- Add message to get people to read the documentation before uploading zip files
=> Fixes for font uploads #2884

html/js/overlay/fields/oe-field.js, html/js/overlay/fields/oe-fieldmanager.js, html/js/overlay/fields/oe-text.js, html/js/overlay/oe-config.js, html/js/overlay/oe-uimanager.js, scripts/modules/allsky_overlay.py
Fixes for
- Colour error in the allsky.log file
- Changes to defaults in the overlay editor are now correctly reflected in any fields using the defaults. Note this applies to ALL defaults not just the colours
=> fixes for font and field defaults #2886

config_repo/requirements.txt
Fix for Python dependencies on 32 bit Bullseye
Tested on 32 Bit Bullseye Lite and Desktop, 64 Bit Desktop
=> Fix for Python dependencies

html/index.php, html/public.php
This removes the flicker when loading a new image in Firefox by decoding the image data in a separate image object before updating the `src` attribute of the live view container.
=> Eliminate flicker in firefox brower

html/allsky/functions.php, html/allsky/index.php, html/allsky/show_thumbnails.php, html/includes/allskySettings.php
The Website and WebUI both use "settings_str" and "settings_array" to refer to their settings file, but the settings files are different - configuration.json for the Website and setting.json for the WebUI.
Since the WebUI "allskySettings.php" page can use "functions.php" from the Website we need to distinguish between the settings files.
=> Rename settings_str to website_settings_str

config_repo/Makefile
This allows users to simply type the name of commands instead of full path name.  It also makes it easier to explain what to do.
=> Update Makefile: add $ALLSKY_SCRIPTS to PATH

src/ASI_functions.cpp
Including the count makes the message appear multiple times in the message section of the WebUI.
=> Update ASI_functions.cpp: don't include error count in message

html/allsky/controller.js
This fixes #3161.
1. Use the correct count to substr() in 4 places.
2. Allow comma for decimal point but convert to period because that's what virtualsky needs.  Users will only see this conversion if they view the location in the virtualsky, which is off by default.
=> Update controller.js: 2 bug fixes - see description

scripts/modules/allsky_shared.py
Fixes an edge case where a user has a decimal separator other than a full stop but still uses a full stop i.e.
Locale is set to de_DE.UTF-8 which has a dp separator of , 
The user enters their lat as 52.1N
=> #3185 Fixes for locale dp separator

install.sh
Copies python dependencies from an old allsky installation during an upgrade. This is required to ensure that the flow upgrader can load the python modules
=> Copy python dependencies during upgrade

config_repo/options.json.repo
I accidentally added the typos when trying to change uppercase letters.
=> Update options.json.repo: fix typos

html/includes/liveview.php, html/index.php, html/public.php
On extremely slow connections you can have multiple image requests stacked up on top of each other -- and even resolve in different orders, which means that you can (in the worst case!) have image sequences that appear to run backwards!
This uses tail recursion to schedule the next iteration of the live image loop after the previous image data has been successfully decoded and the DOM updated, _or_ the image has errored out.
=> Use tail recursion to load next image

src/allsky_common.cpp, src/include/allsky_common.h
Not sure why I added these variables to the capture program.  They were never used.
Probably because they are to be moved from config.sh to settings.json and I wasn't thinking.
=> Don't need savedaytimeimages and savenighttimeimages

scripts/modules/allsky_overlay.py
If the lat or long passed into `_covertLatLon()` was a number then trying to get `input[-1]` fails since it only works on string.
=> Update allsky_overlay.py: check for string before treating as string

allsky.sh, config_repo/config.sh.repo, html/documentation/settings/allsky.html, scripts/check_allsky.sh, scripts/functions.sh, src/Makefile, src/UHUBCTL_LICENSE, src/capture_ZWO.cpp, src/uhubctl.c
This command is used to reset a USB port and is used when a ZWO camera has "too many" errors.
It can also be used manually to display what's connected to USB ports.
=> Add the uhubctl command

src/capture_ZWO.cpp
Putting a value like numTotalErrors in a Log(0, ...) message means it's always changing in the WebUI. Removing it allows the WebUI to display the message once with a count of the times it's seen that message. Still output the numTotalErrors to the log however.
Fixes #3350
=> Update capture_ZWO.cpp: don't include Total Errors in message

html/documentation/changeLog.html, scripts/removeBadImages.sh
Fixes #3368 
When taking darks, remove any image that has a mean brightness > 1.00 (out of 100).
That number may need to be tweaked.
=> 3368-Remove darks that are "too bright"

install.sh
The "mkdir -p" of the three thumbnail directories was done only if there was a prior Website.  They should always be created so they are there if needed.
=> Update install.sh: Move mkdir -p

html/documentation/changeLog.html, html/includes/allskySettings.php
Some changes don't impact the `capture_*` programs so there's no reason to restart them when the setting changes.
Every time an image is processed the settings are re-read.
=> Only restart allsky when needed

html/includes/allskySettings.php, html/includes/editor.php, html/includes/functions.php, html/index.php, scripts/postData.sh
Improve the messages displayed after changing settings.
* Indicate if Allsky was restarted, and if not, why.
* Indicate how many settings were changed, if any.
Run `postData.sh` after any change if there's a local and/or remote website, so the updated settings.json file can be uploaded.
NOTE: Uploading to a remote Website takes at least several seconds.  Perhaps this should be done in the background, and if it fails, add a message via addMessage.sh ?
=> Better messages after changing settings

config_repo/options.json.repo, html/documentation/changeLog.html, html/documentation/knownIssues.html, html/documentation/settings/allsky.html, install.sh, src/ASI_functions.cpp, src/allsky_common.cpp, src/capture_RPi.cpp, src/capture_ZWO.cpp, src/include/allsky_common.h
Offset isn't very useful and is only on ZWO.  Users can fake it some by adjusting the target mean and/or stretching.
Brightness isn't needed - users should adjust target mean instead.
=> Delete brightness and offset settings

html/documentation/changeLog.html, html/documentation/settings/allsky.html, html/includes/allskySettings.php, scripts/check_allsky.sh, scripts/removeBadImages.sh, scripts/saveImage.sh, src/allsky_common.cpp, src/capture_ZWO.cpp
Some people set REMOVE_BAD_IMAGES=false then have problems with timelapse due to a zero length file that could have been caught if the setting was enabled.
This PR removes that option and ALWAYS calls removeBadImages.sh.  If users want to disable the brightness checks they still can, but the check for corrupt images will still be done.
Since ${AS_MEAN} contains the mean brightness calculated by the capture program, there's no reason for removeBadImages.sh to recalculate the mean (unless it's checking a whole directory).  This makes it a second or two faster, plus synchronizes the MEAN displayed on overlays (from the capture program) with what removeBadImages.sh is using to determine if an image is "too light" or "too dark".
This required setting the ZWO MEAN value to a number between 0.0 …
=> Always call removeBadImages.sh and related changes

config_repo/options.json.repo, html/includes/allskySettings.php, html/includes/createAllskyOptions.php, install.sh
* These fields are not editable by the user in the WebUI - they are changed in the Overlay Editor but are stored in the settings file.
* install.sh adds the settings to all settings files with a value of "" if not already there.
* Needed to add a "settingsonly" field to the options.json file that tells the WebUI not to display the setting but make sure it's in the settings file.
* Also needed to put the "display" and "settingsonly" fields as the 2nd and 3rd fields in the options file (if specified) so all the other fields except "type" can be ignored.
=> Add daytimeoverlay/nighttimeoverlay

html/includes/moduleutil.php, html/js/modules/modules.js, scripts/flow-runner.py
Move the flow debug information from the main flow config files into a new file. This is to prevent the main flow files being corrupted which has been reported by a number of people.
=> #3586 Move module debug data to new file

config_repo/options.json.md, config_repo/options.json.repo, html/includes/allskySettings.php, scripts/createAllskyOptions.php
We sometimes need to know the actual type of a setting of type "select", for example, when we need to decide if it should be quoted in a json file.
This PR changes the type of "select" to "select_integer" or "select_text", where the string after the "_" is the actual type.
=> Set actual type of select items

install.sh, scripts/installUpgradeFunctions.sh
If `allsky-OLD/tmp` is mounted when upgrading, unmount it so when users try to remove it, they can.
=> Fix unmounting of ${ALLSKY_TMP}

html/js/jquery-overlaymanager/jquery-overlaymanager.js
Overlay template filenames can be wider than a col-md-6, so make it col-md-12 so it's full width:
=> Update jquery-overlaymanager.js: Make "Filename" field wider

html/documentation/css/custom.css
Made the light theme lines brighter and the dark theme lines darker. The lines are less noticeable in both cases.
ALEX: LET ME KNOW HOW THIS LOOKS.
I don't use dark theme so feel free to make the lines slightly darker.
=> Update custom.css: change --rowSeparator[-dark]

html/cgi-bin/format.py, scripts/flow-runner.py, scripts/modules/allsky_overlay.py, scripts/modules/allsky_shared.py
Fix support for locales
If we are happy with this will need to update the docs.
Testing is fairly easy
- Set a local using raspi-config (say de_DE.UTF-8)
- Reboot pi
- Add field to overlay, manually create a extra json file containing some variable with a number in it i.e.
{
"alex": 1345345.56
}
- Set the format for the field to %.2f and check the value is correctly displayed
- Switch to a different locale and repeat the test
=> #3769 Fix locale support in overlays

config_repo/options.json.repo, html/documentation/explanations/darkFrames.html
Tester James pointed out misleading information in the WebUI.  I replaced it with a link to the dark frames documentation page.
=> Link to dark frames documentation

install.sh, scripts/installUpgradeFunctions.sh
It seems that the initial permissions on the /var/lib/php/sessions directory still work after an allsky upgrade so we don't need to worry about them.
Test process
1) Install clean copy of bookworm lite
2) Install git
3) Clone allsky
4) Install master branch
5) Set settings and allow it to capture a few images (Its nighttime)
6) Stop allsky and allskyperiodic
7) unmount ~/allsky/tmp
8) Move allsky to allsky-old
9) Clone allsky repo
10) Checkout this branch
11) Install Allsky
12) Save setting (worked fine)
The code checks to make sure that the php sessions are being using the filesystem, the only time this will not be the case is if the user has moved the sessions somewhere else such as redis in which case we don't need to do the check.
If any sessions are found to NOT be owned by the web …
=> 3710 upgrade issue with sessions

install.sh
Some testers' installation failed while doing and "apt-get install" on the lighttpd package because the apt lock file was locked. This PR checks if the file is locked before doing an apt-get.
There is a tiny chance that the file becomes locked after our check but before we run apt-get; I can live with that chance.
=> Update install.sh: check for apt-get being locked

html/includes/module.php, html/includes/moduleutil.php, html/js/modules/modules.js
Removes ability to upload modules
=> #3867 Remove module upload functions

install.sh
Fixes gpio control on the pi 5.
Tested on the pi4 and 5 using kernels 6.6.31 and 6.6.51
If a pi 5 is detected the lgpio is installed. adafruit-blinka is supposed to install the correct library but its doesnt seem to do so. IF adafruit fix this then we can revert this fix.
The code uses gpiozero to detect the pi version as this decodes the pi revision number so can detect all future versions of the pi 5 as well.
=> 3923 fix gpio support on pi 5

config_repo/overlay/config/overlay-RPi.json, config_repo/overlay/config/overlay-RPi_HQ-4056x3040-both.json, config_repo/overlay/config/overlay-RPi_Module_3-4608x2592-both.json, config_repo/overlay/config/overlay-RPi_Version_1-2592x1944-both.json, config_repo/overlay/config/overlay-ZWO_ASI178MC-3096x2080-both.json, config_repo/overlay/config/overlay-ZWO_ASI178MM-3096x2080-both.json, config_repo/overlay/config/overlay-ZWO_ASI290MC-1936x1096-both.json, config_repo/overlay/config/overlay-ZWO_ASI290MM-1936x1096-both.json, config_repo/overlay/config/overlay-ZWO_ASI585MC-3840x2160-both.json, config_repo/overlay/config/overlay-ZWO_ASI676MC-3552x3552-both.json
* All overlay templates now include CAMERA_TYPE / CAMERA_MODEL.
* All ZWO templates now include SENSOR temp.
* Enlarged fonts on high-resolution cameras
=> Overlay repo fixes

scripts/modules/allsky_overlay.py, scripts/modules/allsky_shared.py
Fixes #3950
**allsky_overlay.py** should check for errors when reading the `fields.json` or `userfields.json` files and log a useful message.
While fixing this, I found that the log() function needs to escape single quotes in the text passed to addMessage.sh, since it's passed via the shell command line.
=> Check for errors when reading 'fields' files

src/ASI_functions.cpp, src/allsky_common.cpp
The Camera Model was displayed twice in the debug log.
Only display once.
=> Don't display camera model twice

html/includes/datautil.php, html/includes/save_file.php
raspap.php doesn't exist and trying to include it causes an error message in the lighttpd log file.
RASPI_ADMIN_DETAILS is already defined in functions.php so don't redefine it.
=> Fix raspap.php and RASPI_ADMIN_DETAILS

config_repo/options.json.repo, html/documentation/settings/allsky.html
The name "Focus Mode" is misleading.  While we will eventually have that mode, we don't now.  That setting really just determines the focus and puts it in the FOCUS variable.
=> Change "focus mode" to "record focus"

html/includes/functions.php
If a user who had a version of Allsky running and then does a `git clone ...` but does not run `install.sh`, if they try to bring up the WebUI they'll get an incorrect error message.
This is rare, so don't bother trying to determine if Allsky has been installed; instead, just output a better message.
=> Fix error message when the user tries to go to the WebUI but Allsky was not installed

html/allsky/viewSettings.php
If a user goes to a Website that has never been enabled, the files in the "viewSettings/" directory won't exist, and they'll get a somewhat useless message.
Improve the message by telling them how to fix the problem.
=> Update viewSettings.php: improve message

scripts/checkAllsky.sh
When checkAllsky.sh output is displayed in the WebUI there is no space between messages so it's hard to read. Fix by adding a blank line between messages.
Fixes #4022
=> Update checkAllsky.sh: Separate messages when in WebUI

html/documentation/css/custom.css, html/includes/allskySettings.php
If no settings are changed in the WebUI but the user clicks on "Save changes", the message saying no changes were made isn't very easy to see, especially if there are other messages.
=> Make "no changes" message easier to see

scripts/installUpgradeFunctions.sh
If the installation log file doesn't exist and we try to write to it, we'll get an error.
=> Update installUpgradeFunctions.sh: Create file if needed

install.sh, scripts/functions.sh
Fixes #4013
If none of rpicam-still, libcamera-still, and raspicam-still exist and the user has an RPi camera, they will see a message saying, "no camera detected", when the real problem is none of those commands exist.
Fix that by telling the user no commands exist.
=> Say when no RPi command was found

install.sh, scripts/functions.sh
Only run determineCommandToUse() once.  It's possible that it can take up to a minute to run so only running once potentially saves time.  It also may output a message on error, and we only want to see the message once.
This must be run AFTER PR #4026
=> Don't run determineCommandToUse() if already run

.github/ISSUE_TEMPLATE/2-bug_report.yml
Many people who enter Issues for installation-related problems don't attach allsky/config/logs/install.log, which is almost always needed to debug the problem.
This change mentions attaching that file.
=> Update 2-bug_report.yml: mention attaching "install.log" if needed

install.sh, scripts/installUpgradeFunctions.sh, scripts/makeChanges.sh
When enabling a local Website, some data files are copied to the "viewSettings" directory.
However, if the user already had a local Website, during installation those files aren't copied and should be.
=> Run postData.sh during installation if needed

scripts/removeBadImages.sh
Zero-length or corrupted images also cause timelapse generation to fail.
=> Update removeBadImages.sh: include timelapse in Usage message

scripts/functions.sh
Fixes #4031
Another old ASI120 camera that has "ASI120 Planetary Camera" as the USB name but "ASI120" as the name reported by the camera itself.
=> Check for "Planetary Camera" in ZWO model name

scripts/generateForDay.sh
Also, fix a minor bug with not doing timelapse if startrails fails.
=> Update generateForDay.sh: remove thumbnail prior to generating timelapse

install.sh
This change removed the rpi.gpio module on the pi5. The pi5 requires the lgpio module.
Test on a pi4 and pi4 to ensure i2c based temperature sensors can be read
There is also a change to the module installer that has already been merged as reinstalling some modules will cause the rpi.gpio module to be reinstalled !
=> 4048 bug remove rpigpio during installation on the pi 5

scripts/timelapse.sh
Fixes #4028 
For some reason, ffmpeg can be killed but we don't get a "Killed" message, but the return code is 137.  Check for that.
=> Update timelapse.sh: check for return code 137

remoteWebsiteInstall.sh
so it's always there.  Prior to the fix, removing the test file failed if a remote port was specified.
Fixes #4059
=> Update remoteWebsiteInstall.sh: Add -p to REMOTE_PORT earlier

remoteWebsiteInstall.sh
The AllskyVersion setting should always be updated whenever remoteWebsiteInstall.sh is run to keep it in sync with the main Allsky.
=> Update remoteWebsiteInstall.sh: Update version

html/js/jquery-gpio/jquery-gpio.js
GPIO10 was incorrectly configured as as GPIO18 so selecting GPIO18 would select both GPIO10 and 18
This fix corrects the config of GPIO10
=> #4071 Fix incorrect gpio pin configuration

scripts/flow-runner.py
When debug level 4 is set the flow runner will not trap any exceptions thrown in modules. This make sit far easier to find issues
=> #4074 Don't trap errors at log level 4

remoteWebsiteInstall.sh, variables.sh
Fixes #4084
Several fixes and enhancements to remoteWebsiteInstall.sh.  See each commit for details.
=> remoteWebsiteInstall.sh fixes

html/css/overlay.css
The "Allsky is not currently capturing images" message is difficult to see in the Overlay Editor in Light mode because the image background and the message background are similar shades.
This PR lightens the image background.
=> Update overlay.css: change opacity

scripts/modules/allsky_shared.py
Changes the way the extra data files are saved. Rather than write directly to the file data is first written to a temporary file and then this file moved to the.
To test this
1) Delete all of the extra data files
2) Ensure that the extra data files are recreated and contain the correct data
3) Check the permissions on the extra data files 0x644
=> #4087 Change was extra data files are saved and pylint the code

config_repo/allsky.logrotate.repo
Changed logrotate config
Tested over a few days on my pi and is fine
To test this you must set the logs to rotate daily otherwise you will have to wait a week to see if its worked !
Daily rotation
```
/var/log/allsky.log
{
rotate 2
daily
missingok
notifempty
compress
delaycompress
sharedscripts
postrotate
systemctl kill -s HUP rsyslog.service
endscript
}
/var/log/allskyperiodic.log
{
rotate 2
daily
missingok
notifempty
compress
delaycompress
sharedscripts
postrotate
systemctl kill -s HUP rsyslog.service
endscript
}
```
=> #4109 Fix logrotate

config_repo/options.json.repo, html/documentation/changeLog.html, html/documentation/settings/allsky.html, install.sh, scripts/generateForDay.sh
Not allowing the names to change simplifies configuring a remote Website and makes it similar to local Websites.
One user already had problems after he changed the names.
=> 4134 don't allow changing remotewebsite{timelapse | keogram |startrails} names

install.sh, scripts/installUpgradeFunctions.sh
Fixes #4165 
Don't show the value of the REMOTEWEBSITE_HOST, REMOTEWEBSITE_USER, or REMOTEWEBSITE_PASSWORD in the installation log file.
=> 4165 the username and password should not appear in installlog

config_repo/options.json.repo, html/documentation/css/custom.css, html/documentation/settings/allsky.html
Fixes #4110
Describe how `Max Auto-Exposure` interacts with `Consistent Delay Between Images`.
=> 4110 documentation for max auto exposure needs to mention consistent delays between images

config_repo/options.json.repo, src/ASI_functions.cpp, src/allsky_common.cpp, src/capture_ZWO.cpp, src/include/allsky_common.h.repo
The `gamma` setting only applies to ZWO, and does not appear in the WebUI so is never set.
This PR removes the unused code for it.
=> Remove gamma setting

html/js/overlay/oe-config.js
@Alex-developer,
the hard-coded path `~/allsky/config/overlay` should be replaced by a javascript version of ${ALLSKY_OVERLAY}.
Ditto for any other hard-coded paths in javascript.
=> Update oe-config.js: Fix incorrect file name reference

install.sh, scripts/installUpgradeFunctions.sh, scripts/utilities/allsky-config.sh
Fixes Issue #4273
Changing swap size or whether or not ~/allsky/tmp was in memory after installation didn't work.  I'm pretty sure it used to so am not sure what changed.  Either way, this PR greatly improves the user experience.
=> 4273 fix recheck_tmp and recheck_swap in allsky config

html/execute.php, scripts/functions.sh, scripts/utilities/allsky-config.sh, scripts/utilities/execute.sh, scripts/utilities/showStartTimes.sh
Allow "show_start_times" to accept a "--no-header" option which doesn't display the header.
Also, add "allsky-config" to the list of commands that can be executed via "execute.php".
This allows other programs to get the sunrise and sunset times.
=> Add   no header to allsky config's "show start times"

scripts/testUpload.sh
This is so it passes "null" to upload.sh instead of not passing anything, thereby hosing up the command-line arguments.
=> Update testUpload.sh: Fix: force ${DIR} to be "null" instead of ""

scripts/generateForDay.sh
Also add a "TODO" statement for a future optimization to this and other shell scripts that call "settings()" multiple times, to instead get ALL the settings via one command that reads the settings file just once.
Fixes Issue #4660
=> Update generateForDay.sh: Fix handling of "--nice n"

html/documentation/css/custom.css
Alex,
Lowering the z-index for several WebUI things fixed some of the problems I saw where dialog boxes and other items were behind things, because bootstrap was using a z-index of something like 1024.
=> Update custom.css: Lower z-index

scripts/saveImage.sh, src/allsky_common.cpp
It's more efficient for the capture programs to pass the RESOLUTION to saveImage.sh than for saveImage.sh to calculate it.
=> Output RESOLUTION_Z and RESOLUTION_Y

html/includes/functions.php, install.sh, scripts/convertJSON.php
The `install.sh` scripts needs to call create_variables_json() before any .php file is called, because they include "functions.php" which produces an error if variables.json doesn't exist.
It used to produce that error with HTML tags which made it almost impossible to read while running install.sh.
=> Add --from-install

html/includes/moduleutil.php, scripts/modules/allsky_overlay.py, scripts/modules/allsky_shared.py, scripts/modules/allskyoverlay/overlaydata.py, scripts/modules/allskyvariables/allskyvariables.py, variables.sh
Move the extra data folder into the Allsky tmp folder.
Notes:
- This will improve performance as the Allsky tmp folder is in memory
- Extra data will be lost during a reboot or upgrade
- The code uses atomic writes to prevent partial files being read by the overlay  module. The atomic writes have also moved from /tmp to the alley tmp folder
- A side effect of these changes also fixes the inability to add user variables
=> 4789 move extra directory to allsky tmpextra
