AllskyTeam/allsky

- Makefile
- keogram.cpp
- startrails.cpp
Hi, this pull request includes C++ and OpenCV versions of keogram and startrails composition which are way faster than the script based ones and easier on the SD card as they accumulate the frames in memory and only write out the final output. I didn't include modified scripts but these take the same parameters in same order and so on. In my own tree I've also modified the scripts to upload the images to a remote server.
> C++ and OpenCV versions of keogram and startrails composition

- keogram.cpp
This change adds a simple dashed line and hour label to keogram which makes it easier to correlate local time and lines in the keogram.
> Draw a vertical line and hour labels into keogram

- capture.cpp
Reformatted capture.cpp for easier reading and maintenance.  Followed same code formatting from keogram.cpp and startrails.cpp.
> Reformatted for easier reading / maintenance.

- capture.cpp
Just adding myself to the contrib list...
> Added /me to contrib list inside capture.cpp

- asi.rules
- install.sh
* Added start/stop of systemd unit file for allsky with camera plug/unplug events
* Changed install path of asi.rules to User area ( /etc/udev/rules.d ) instead of base OS area ( /lib/udev/rules.d )
* Added 'udevadm control -R' to reload udev rules after install of asi.rules
> Updated udev rules, changed udev rule install location

- gui/install.sh
* Moved settings.json to /etc/respap for GUI install
* Put sudoer's entries in /etc/sudoers.d/ instead of main sudoers file
> Changed settings path to /etc/raspap, misc

- scripts/endOfNight.sh
- scripts/removeBadImages.sh
Fixes thomasjacquin/allsky#120
> Tool for removing corrupt images before generating keograms and startrails

- scripts/allsky_mfs.sh
Inspired by thomasjacquin/allsky#104
> Scripted tmpfs/overlayfs to protect sdcard

- .gitmodules
- Makefile
fixes thomasjacquin/allsky#123
> compile sunwait on non-arm platforms

- README.md
- install.sh
* tell users to do a recursive clone to save having to initialize the git submodule
* added some whitespace to improve legibility of `install.sh`
* reordered the steps to compile allsky before making too many system changes.
> A little bit of additional documentation

- capture.cpp
1. fixes #96 asi120mc bug: frame broken into split parts
2. fix asi120mc bug: 2 frames delayed after exposure time change
> Bypass 2 bugs in the design of ASI120MC

- README.md
- config.sh.repo
- scripts/saveImageNight.sh
Quick change to stretch the image via config settings, eases the upgrade process.
> Stretch image via config rather than edit scripts

- scripts/removeBadImages.sh
I'm rebuilding my allsky system (yet again) and this time some of the back end processing is being done on my workstation with more cores, more memory, a proper SSD, adequate cooling .... and so, I'll just run all the cores. That's what I bought 'em for!
> support parallel image cleaning

- scripts/endOfNight.sh
y'know, to reprocess historical data.
> allow endOfNight.sh to be run with an arbitrary date

- capture.cpp
Fix extra age not working when 0
> Fix extra age not working when 0

- gui/install.sh
Fixes for setting the hostname correctly. 
The original change was not expanding the hostname variable when updating the hosts file and I totally missed the avahi config
> HOTFIX: Fix incorrect mdns name

- allsky.sh
And removed some unneeded commented-out lines.
> Removed debug "echo"

- config.sh.repo
Removed "<<<<< HEAD" and a couple other change control lines.  Not sure how they got there.
> config.sh.repo had change control in it

- gui/lighttpd.conf
> add cache control header for liveview image

- keogram.cpp
- startrails.cpp
You've seen this idea in `multi_out`, here it is for keogram and startrails. Applying this to capture will come later.
> Config structs

- capture.cpp
> Count ASI_ERROR_TIMEOUTs

- capture.cpp
- capture_RPiHQ.cpp
> Capture segmentation fault

- scripts/upload.sh
Fixes #525 
This is a hot one - uploads are failing due to it.
> upload.sh: Set default ALLSKY_DEBUG_LEVEL

- Makefile
> Fixed opencv pkg-config complaints

- config.sh.repo
so other scripts, like upload.sh, can use it.
> config.sh.repo: Set ALLSKY_DEBUG_LEVEL

- scripts/timelapse.sh
fixes thomasjacquin/allsky#531
> typo in "sequence"

- scripts/timelapse.sh
> timelapse.sh: fix bug in $DIR

- src/Makefile
Fixed typo in settings_RPiHQ.json install path.
> Fixed settings_RPiHQ.json install path

- scripts/endOfNight.sh
> Fixed missing KEOGRAM conditional

- scripts/endOfNight.sh
> endOfNight.sh: startrails BUG

- src/Makefile
> Copy capture_RPiHQ to $ALLSKY_HOME

- scripts/copy_notification_image.sh
- scripts/endOfNight.sh
- scripts/generateForDay.sh
- scripts/postData.sh
- scripts/saveImageDay.sh
- scripts/saveImageNight.sh
- scripts/upload.sh
> 2 letter upload

- src/capture.cpp
> capture.cpp: getTickCount

- website/install.sh
> Check that WebUI is installed

- website/install.sh
> install.sh: bug-fix with comma

- allsky.sh
- config_repo/config.sh.repo
- src/Makefile
- src/capture_RPiHQ.cpp
- src/include/RPiHQ_raspistill.h
- src/include/mode_RPiHQ_mean.h
- src/mode_RPiHQ_mean.cpp
for review
my try to fix the exposure problem mit RPiHQ / raspistill
* with keograms you can see the exposurecontrol working  https://www.astro-fotografie.at/allsky2/keograms/ 
* no daily videos to save webspace.
* some additional parameter missing (todo), but it works with default values - for me ;-)
>  capture_RPiHQ_li 

- config_repo/config.sh.repo
Please merge this to to deactivate autoexposure all the time - sorry for that bug
> I_791_CAPTURE_EXTRA_PARAMETERS: set empty defaultvalue

- README.md
allsky.sh is in allsky, not allsky/scripts
> Incorrect directory in README.md

- src/keogram.cpp
please review und try/test before merge.
> keogram: (cleanup/enhancement) support mono images

- src/capture_RPiHQ.cpp
Work with either command, depend on the "-cmd" option
> capture_RPiHQ.cpp: support libcamera and rapsistill

- src/capture.cpp
Please test this capture.cpp before approving.
The new variables (dayskipframes, nightskipframes, and aggression) will be added to the .json files later.
> Capture.cpp updates and fixes

- scripts/generateForDay.sh
Fix calculation of $EXIT_CODE so it's never negative
> generateForDay.sh: bug fix $EXIT_CODE

- src/Makefile
> Adding missing bc to deps

- scripts/saveImage.sh
If we're not saving daytime images, delete the copy in allsky/tmp when done with it.
> saveImage.sh: rm tmp file if not saving in daytime

- scripts/darkSubtract.sh
I accidently merged the prior PR that didn't completely fix the issue.  This PR does.
> darkSubtract.sh: remove leading zeros, part 2

- .gitignore
- src/keogram.cpp
https://github.com/thomasjacquin/allsky/discussions/909
> enhancement:  min. limit for keogram expand

- scripts/darkSubtract.sh
This change goes with the one to saveImage.sh and darkCapture.sh.
> darkSubtract: use AS instead of THIS

- scripts/saveImage.sh
This should be the final bug fix.  allsky/tmp files are no longer left there and images are correctly put in allsky/images/DAY.
> saveImage.sh: bug fix: rm tmp files

- config_repo/config.sh.repo
Not sure how I managed to add 2 copies.
> Remove duplicate FAN_DATA_FILE

- scripts/postData.sh
- website/install.sh
Create a new data.json file when creating a new website or updating an existing one.
> data.json check

- src/startrails.cpp
Fixes #734 
Fix bug where startrails crashed if images with different number of channels were in the same directory.
Make startrails.cpp more like keograms.cpp to aid in maintenance.
> Startrails fix

- config_repo/ftp-settings.sh.repo
- scripts/saveImage.sh
Allows users to copy image.jpg to a local directory as well as FTP'ing elsewhere.
> WEB_IMAGE_DIR

- allsky.sh
- config_repo/config.sh.repo
Replace the FAN_DATA_FILE with WEBUI_DATA_FILES which is a generic way to add data, progress bars, and/or buttons to the WebUI "System" page.  The old FAN_DATA_FILE variable only supported adding fan data.  The new mechanism is much more generic and powerful.
There is a related PR in the allsky-portal package to implement the code changes.
> config.sh.repo: WEBUI_DATA_FILES

- scripts/generate_notification_images.sh
* New "--directory dir" argument to specify the directory the image(s) should be created in.  Default is $PWD.
* Add usage_and_exit() function to centralize displaying Usage message.
* Add "--help" option to be consistent with other commands.
* Add "--quality 100" to "convert" to minimize compression artifacts.
* Only display "Creating..." message when called from command line, so the message doesn't appear in the Allsky log.
> generate_ notification_images.sh: misc changes

- src/keogram.cpp
Not the first picture of an hour is also the beginning of an hour!
We still have to watch the hour change.
> bugfix-keogram-annotation

- scripts/saveImage.sh
> saveImage.sh s/{$/${/

- src/capture.cpp
a gazillion little changes, but no functionality changes.
> Capture.cpp spaces to tabs

- scripts/upload.sh
This line should never have been removed.
> Upload.sh: restore line

- variables.sh
* Not sure why I ever called them PORTAL_DIR and WEBSITE_DIR when everything else is ALLSKY_*.
* Leave old names there for compatibility, but remove after the next major release.
> variables.sh: rename variables

- gui/install.sh
* This allows the "Editor" tab in the WebUI to edit the config.js and virtualsky.json files in the Allsky Website, if installed.
* Changes to lighttpd to create a "/website/" alias are in a separate PR.
* Changes to the WebUI are in a PR in allsky-portal.
> install.sh; update XX_ALLSKY_WEBSITE_XX

- scripts/removeBadImages.sh
* Perform error checks of the `convert` command.  A user had this issue.
* Don't create temporary files in the vast majority of the cases.
> Remove bad images.sh error checks + improvement

- src/allsky_common.cpp
A more efficient and cleaner way to calculate DAY or NIGHT is to use the exit code from sunwait, rather than parsing its output.
> Better calculateDayOrNight()

- src/allsky_common.cpp
For the `system()` function, non-zero exit codes are stored in an upper byte, so need to use macros to get to them.
> allsky_common.cpp: properly check exit code

- scripts/reload.sh
Comment out echo.  It's for debugging.
> reload.sh: Comment out echo

- src/capture.cpp
- src/capture_RPiHQ.cpp
> Fix locale placement

- src/allsky_common.cpp
* Also use single quote for thousands separator.
> allsky_common.cpp: Handle quotes

- scripts/postToMap.sh
Handle maximum number of updates.
This will need to be tested and possibly modified when the server supports this feature.
Ditto for errors.
> Max number of updates

- allsky.sh
- variables.sh
These codes are used in several scripts, so centralize them.
> variables.sh: add EXIT codes

- src/capture.cpp
- src/capture_RPiHQ.cpp
SIGUSR1 isn't used in Allsky, so remove references to it in the capture programs.
> Remove SIGUSR1

- README.md
The "scripts/" should not have been there.
> README.md scripts bug fix

- gui/lighttpd.conf
Add "thumbnails" directory so the Website thumbnails appear as they are being created.
> lighttpd.conf: add thumbnails directory

- gui/lighttpd.conf
* General cleanup: remove commented-out lines, combined multiple lines into one to be consistent, changed couple spaces to tabs.
> lighttpd.conf: remove unneeded lines

- website/install.sh
At least one user had this problem
> install.sh: don't assume login is called "pi"

- scripts/saveImage.sh
> saveImage.sh: don't output "DEBUG"

- src/allsky_common.cpp
- src/capture.cpp
- src/capture_RPiHQ.cpp
- src/include/allsky_common.h
* Output string version of "flip".
* Many others - see individual commits.
> Capture better messages

- scripts/postData.sh
If the first "source" fails, they'll probably all fail, so exit.
> postData.sh: check for failed "source"

- src/capture.cpp
* Camera mode, ID, and serial #.  This moved quite a few lines of code.
* Indent the ControlCaps output to match camera info.
* BUG FIX: Rename "called" to "set_auto_exposure" to better reflect what it does, and make global so it can be set when going from day to night and vice versa.
> capture.cpp: put all camera attributes together

- gui/lighttpd.conf
The missing / causes WebUI not to display anything.
> lighttpd.conf: restore missing /

- gui/install.sh
Need to remove trailing "_XX" from placeholder.
> install.sh: BUG FIX: ALLSKY_SCRIPTS

- install.sh
* Use braces { }
* chmod 755 of $ALLSKY_HOME since some versions of Linux default to 750 so web server can't read it.
> Install.sh minor changes

- scripts/postData.sh
Need to set ${ALLSKY_HOME} so the script can be run by the web server.  Otherwise users get error messages.
> postData.sh: Bug fix: Allow to be run by WebUI

- src/capture.cpp
- src/capture_RPiHQ.cpp
Rename to "variableName" format to be consistent with other variables.
> Capture-rename variables

- src/capture_RPiHQ.cpp
* Implement currentMaxAutoexposure_us as is done in ZWO code.
* If "-daymean" or "-nightmean" are > 0.0, then use the modeMean auto exposure/gain method, otherwise use the camera auto exposure/gain.
* Fix "-save_dir" argument typo
* Make sure current auto exposure isn't greater than max auto exposure
> capture_RPiHQ.cpp: currentMaxAutoexposure_us

- scripts/postData.sh
to try and merge pending master changes into dev
> postData.sh: temporarily revert to master version

- html/camera_options_RPiHQ.json
- html/camera_options_ZWO.json
> Enable dayawb

- src/capture.cpp
* Only set max auto gain/exposure if using auto gain/exposure.  They aren't used otherwise.
* Use ASI_AUTO_TARGET_BRIGHTNESS, which sets the auto exposure target brightness and matches the "Brightness" WebUI setting, rather than ASI_BRIGHTNESS which is an alias for ASI_OFFSET which adds a certain amount to each pixel.
* Get cameraMaxExposure_us and ensure exposures never exceed it.
* Added a comment for clarification
> capture.cpp: auto gain/exposure changes

- src/include/allsky_common.h
Also make a couple words upper case to be consistent
> allsky_common.h: support EXIT_NO_CAMERA

- scripts/upload.sh
> upload.sh shellcheck fix

- scripts/endOfNight.sh
- scripts/postData.sh
The variable name changed in variables.sh and I forgot to change it here, too.
> Use ALLSKY_WEBSITE

- src/capture.cpp
- src/capture_RPiHQ.cpp
* Change "const char" to "char const" for consistency.
* A few indentation fixes.
* Added a few comments.
* Set error output to go to stderr.
* Moved command-line error checking to outside of loop.
* Added "-version" argument.
> Capture.cpp misc minor changes

- allsky.sh
* Slightly simplify the "lsusb" command argument.
* Pass the -version argument to the capture program.
> allsky.sh: add version

- src/capture.cpp
- src/capture_RPiHQ.cpp
Line up the day and night values in the debug output so it's easier to read.
> Line up capture output

- html/camera_options_RPiHQ.json
There were accidently turned on for RPi.
> camera_options_RPiHQ.json: hide 2 settings

- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/capture.cpp
- src/capture_RPiHQ.cpp
- src/include/allsky_common.h
Added functions to validate command-line arguments and display messages if they are out of bounds.
> Support validate() functions

- src/allsky_common.cpp
- src/capture.cpp
- src/capture_RPiHQ.cpp
- src/include/allsky_common.h
It's a float so we should treat it as such.
> Convert "angle" to float

- .github/ISSUE_TEMPLATE/bug_report.md
Add code to make this Issue template available for new Issues.
> bug_report.md: make available for new Issues

- README.md
Will set to actual date once known.
> README.md: update Release to be generic

- README.md
* Support vi by changing HTML comments and horizontal rules so things vi understands.
* Update the Release Changes.
> README.md: support vi

- html/index.php
to "Allsky Settings" since it contains more than just camera settings, and will over time contain even more non-camera settings.
> index.php: rename "Camera Settings"

- config_repo/lighttpd.conf.repo
Initial creation of file in /documentation.
The files will be updated in other PRs.
> Add allsky documentation

- config_repo/avahi-daemon.conf.repo
- gui/install.sh
More preparation for merging the WebUI installer into main Allsky installation script.
> Web UI install changes # 2

- variables.sh
* Add YELLOW and a DEBUG color
* Add web-based colors for scripts that write to web pages.
> variables.sh: add colors

- html/includes/editor.php
- html/includes/save_file.php
Initial work to aid in supporting remote Allsky Websites by keeping the master configuration file on the Pi where it can easily be edited (and certain variables kept in sync with the settings_*.json files), then uploaded to the remote server whenever there's a change.
> Support remote websites, part 1

- .github/ISSUE_TEMPLATE/bug_report.md
* Fix typo
* Fix length of line so it matches one below it
> bug_report.md: minor changes

- html/includes/camera_settings.php
* Messages should end with period.
* "makeChanges.sh" is included n this release so there's no need to check if it exists.
> camera_settings.php: minor changes

- scripts/postToMap.sh
* Use web colors since postToMap.sh can be called from the terminal window (terminal colors), endOfNight.sh (plain text), or the WebUI (html colors).
* Upload the Allsky version to the map server.
> postToMap.sh: web colors

- src/ASI_functions.cpp
- src/capture.cpp
- src/capture_RPiHQ.cpp
- src/include/mode_RPiHQ_mean.h
- src/mode_RPiHQ_mean.cpp
Implement additional per-camera settings, plus other changes.
Will still need one or two more PRs to finish the per-camera settings.
> Per camera settings

- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/capture.cpp
- src/capture_RPiHQ.cpp
- src/include/allsky_common.h
- src/include/mode_RPiHQ_mean.h
- src/mode_RPiHQ_mean.cpp
* Move a TON of code from capture*.cpp into allsky_common.cpp and replace with function calls.
* Create a "struct config" to hold all configuration variables which required another TON of changes.
> Support commonality

- README.md
- html/camera_options_RPiHQ.json
- html/camera_options_ZWO.json
- src/allsky_common.cpp
New variables available via the WebUI.
> Add variables

- config_repo/config.sh.repo
Most conflicts require the GitHub desktop which I can never get to work, so I'm fixing the conflict by changing the "dev" branch.
> config.sh.repo: fixes to resolve conflicts

- scripts/copy_notification_image.sh
- scripts/upload.sh
Normally we want to abort a second upload if there's already an upload of the same type.
However, with notification images we may want the second notification to wait until the first one is done.
> Allow waiting in upload.sh

- gui/install.sh
* save_file.php now includes functions.php, which does all the define()'s, so there's nothing to replace in save_file.php.
* Add modification of RASPI_CONFIG.
> install.sh: remove save_file.php

- README.md
- allsky.sh
- config_repo/settings_RPiHQ.json.repo
- config_repo/settings_ZWO.json.repo
- html/camera_options_RPiHQ.json
- html/camera_options_ZWO.json
- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/capture_RPiHQ.cpp
- src/include/allsky_common.h
These are for RPi cameras only.
> Add contrast and sharpness

- html/includes/camera_settings.php
- html/includes/system.php
The array is already created in functions.php so other scripts should use it rather than reading the configuration file in again.
> Use global camera settings array

- src/capture.cpp
- src/capture_RPiHQ.cpp
Let the user know how many images will still be skipped.
> Better skip frames message

- src/allsky_common.cpp
- src/capture.cpp
- src/capture_RPiHQ.cpp
- src/include/allsky_common.h
Move a bunch of separate variables to the config structure so they more easily be passed to funtions.
> Add "last" variables

- src/allsky_common.cpp
* Export additional variables.
* Change the name of a few variables.
* Moved some lines so, for example, all the gain-related variables are together.
> allsky_common.cpp: add variables

- config_repo/sudoers.repo
- gui/install.sh
- html/camera_options_RPiHQ.json
- html/camera_options_ZWO.json
- scripts/makeChanges.sh
- scripts/updateWebsiteConfig.sh
Split out the code that updates the Website configuration file into a separate script so it can be used by other scripts.
> Make changes.sh split

- README.md
- config_repo/settings_RPiHQ.json.repo
- config_repo/settings_ZWO.json.repo
- html/camera_options_RPiHQ.json
- html/camera_options_ZWO.json
- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/capture.cpp
- src/capture_RPiHQ.cpp
- src/mode_RPiHQ_mean.cpp
See the README.md files for the meanings of the levels.
> Use consistent debug levels

- src/allsky_common.cpp
sunwait can't accept numbers with commas in them, as is the case in Europe and elsewhere.
Replace the comma with a period in the angle.
> allsky_common.cpp: fix for commas

- html/camera_options_RPi.json
- html/camera_options_ZWO.json
- html/includes/camera_settings.php
- html/includes/functions.php
- scripts/makeChanges.sh
The "takeDaytimeImages" setting needs to send an updated data.json file to the Allsky Website, if there is one.
That and other settings require that Allsky be restarted.
Handle these cases.
> Handle daytime capture changes

- src/ASI_functions.cpp
* The number and order of entries in the ControlCaps enum, argumentNames, and ControlCapsArray must match.  They didn't and it gave a Segmentation fault.
* Ignore  control caps that aren't supported or that have arguments we don't use.
* Fixed names of arguments that changed.
* Moved RPi's argumentNames[] array so it was by its ContolCapsArray since they both need the same number and order of entries.
* The HQ camera has a max exposure of 230 seconds, so used that for max auto-exposure.
> ASI_functions.cpp: inconsistent size bug fix

- html/includes/functions.php
It was missing the 2nd argument
> functions.php: getVariableorDefault() bug fix

- html/includes/editor.php
Put it at the end of the drop-down list, so all the files on the Pi are together.
> editor.php: move remote config file

- src/allsky_common.cpp
- src/capture_RPi.cpp
- src/capture_ZWO.cpp
- src/include/allsky_common.h
Move more code from capture_*.cpp to allsky_common.cpp to aid in future maintenance.
> Move code to allsky common.c

- src/capture_ZWO.cpp
* Changed a few Log() levels.
* Don't need to check if the current exposure is > camera's max - that check was done when the arguments were processed.
* Renamed "reportedExposure_us" to "suggestedNextExposure_us" to better reflect what it is (it's what the camera driver thinks the next exposure should be.
* Added comments.
> capture_ZWO.cpp: minor changes

- src/ASI_functions.cpp
* Add the camera type to the "cameras.txt" file.
* Use Log() instead of writing to stderr.
> change name of "cameras.txt" and use Log()

- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/capture_ZWO.cpp
- src/include/allsky_common.h
Misc. bug fixes and minor changes.
> Capture zwo.cpp bug fixes

- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/include/allsky_common.h
Also, validate the latitude and longitude were specified and they are valid.
> Support latitude/longitude with or without direction

- config_repo/config.sh.repo
- variables.sh
Move from config.sh (which should only contain settings and variables that change) to variables.sh (which contains static variables).
> Move GITHUB_ROOT

- html/includes/liveview.php
Ooops, missed this when adding all the other files.
> add missing html/includes/liveview.php

- config_repo/configuration.json.repo
Add an icon to display the current image full-size.
> Website: add icon for full image

- install.sh
Added "sudo" to several commands for the WebUI (the old gui/install.sh script was run with sudo).
> install.sh: sudo fixes

- src/ASI_functions.cpp
This is consistent with the allsky_options.json file.
> ASI_functions.cpp: set min_delay to 10ms

- install.sh
- variables.sh
Used to get the contents of Github files, like "version".
> Add GITHUB_RAW_ROOT

- website/install.sh
If the user changed it, restore it.
> install.sh: restore any analyticsTracking.js

- website/install.sh
Change permissions, owner, and group after all the files are in the website.
> install.sh: change permissions later

- install.sh
* Fixed typo in function name - should have been save_camera_capabilities()
* Fix bug where $ALLSKY_{OWNER|GROUP} were being used before being set.
> install.sh: bug fixes

- install.sh
* Improved handling of prior Allsky Website - move to new location since they won't work at old location.
* Restore a few more files from prior Allsky.
* Bug fix: source'ing the prior config.sh gave some errors, but we only need the file to get the CAMERA_TYPE, so ignore the errors.
* Bug fix: if updating Allsky, need to source config.sh to get the CAMERA_TYPE.
* Since we move the prior website to the new location before optionally deleting an old WebUI, we don't need to save any old website first.
> install.sh: several more fixes

- website/install.sh
* Add function to display output so  it's done consistently.
* Put all functions at top.
* Split out some code into update_website_configuration_file() that only updates configuration.json, either for a remote or local website.
* Implement ALLSKY_VERSION and WEBSITE_VERSION
> website/install.sh: make more like install.sh

- config_repo/config.sh.repo
- config_repo/configuration.json.repo
- install.sh
- scripts/updateWebsiteConfig.sh
- variables.sh
So we can compare prior copies of user's allsky with the newest one.
> Add $ALLSKY_VERSION

- website/install.sh
* Moved some code around.
* Use nicer looking "Installation is complete" message.
* Other minor stuff
> website/install.sh: misc minor changes

- scripts/updateWebsiteConfig.sh
* This is MUCH better than the prior hack that didn't work with outlier cases.
* Also remove the ability to update the old config.js file.
> updateWebsiteConfig.sh: use jq to update variables

- scripts/saveImage.sh
If we aren't creating mini-timelapse, don't upload them.
> saveImage.sh mini-timelapse bug fix

- src/ASI_functions.cpp
Output the the Camera Capabilities file.
> ASI_functions.cpp: output supported rotations

- config_repo/options.json.repo
* Missed some spaces after ":".
* "checkchanges" is a boolean so should be 0 or 1, like the other booleans.
> options.json.repo: more standardization

- install.sh
* Moved ALLSKY_LOG=  higher because it was being used before it was set.
* Changed "{FILE}" to "${FILE}".
* Run "sudo systemctl force-reload lighttpd" since we get output that it should be run.
* Stop hostapd service before (re)installing it to hopefully get rid of error message.
> install.sh: bug fixes and minor changes

- src/ASI_functions.cpp
"value" and "label" were reversed.
> ASI_functions.cpp: fix bin output

- install.sh
Was only creating the html/includes/allskyDefines.inc file for upgrades.
> Install.sh create web UI locations bug

- install.sh
- scripts/makeChanges.sh
- src/ASI_functions.cpp
- src/capture_RPi.cpp
- src/capture_ZWO.cpp
Fixed to bugs found during installation testing.
See individual commits.
> Various installation fixes

- install.sh
* The menu text ("Camera Type") wasn't appearing due to the height of the menu items being too tall.
* Improved the message.
* Put spaces between 1st and second columns to improve readability.
> install.sh: whiptail menu bug

- src/mode_mean.cpp
He did a great job explaining the mode_mean algorithm so the PR includes those comments for future developers.
> Add algorithm comments from Andreas

- src/ASI_functions.cpp
- src/include/allsky_common.h
* sensor{Width | Height} is for future use - I think I read somewhere that some ZWO cameras have a minimum region of interest of 64 pixels.  However, I'm not sure how we determine that.
> ASI_functions.cpp: add missing "capabilities"

- html/includes/createAllskyOptions.php
It works now - uses the camera capabilities file to create an `options.json` file specific to the camera type/model, and optionally create a default `settings.json` file.
> createAllskyOptions.php: major updates

- config_repo/config.sh.repo
> config.sh.repo: produce info if jq fails

- config_repo/options.json.repo
- html/includes/createAllskyOptions.php
- html/includes/functions.php
- scripts/functions.sh
- scripts/makeChanges.sh
- src/ASI_functions.cpp
A bunch of change to improve/fix creation of the "options.json" and "settings.json" files during installation.
> Improve creation of config files

- config_repo/options.json.repo
* Also add "display: 0" for the XX_END_XX entry so it's not displayed in the WebUI.
> options.json.repo: add cameraModel

- html/includes/createAllskyOptions.php
* Support multiple levels of $debug.
* Add cameraType and cameraModel to settings file.
* Added more debugging output.
> createAllskyOptions.php: misc changes

- scripts/makeChanges.sh
updateWebsiteConfig.sh no longer takes an "OLD_VALUE" argument.
> makeChanges.sh: updateWebsiteConfig.sh bug fix

- src/ASI_functions.cpp
* DefaultValue is set in options.json so we can have different defaults for day and night.
* Add MaxValue
> ASI_functions.cpp: changes values

- html/includes/camera_settings.php
* Check for non-existent fields using getVariableOrDefault().
* Implement "nullOK" to indicate required fields that are empty.
* Implement "readonly" fields.  Currently, only Camera Model is read only.
* Display camera type and model at top of window.
> camera_settings.php: misc additions

- html/includes/functions.php
The "settings.json" file should be writable by the web server, so write to it.  If that fails, create a temp file, but that will break the link.  install.sh makes the files writable by the web server.
> functions.php: fix saving a file

- install.sh
* No need to force user to run in ~/allsky.
* Call save_camera_capabilities as early as possible since it checks that a camera is connected, which the installation needs.
* Use whiptail more often, especially to call attention to something.
* Added code to set the LOCALE.
* Added preliminary code to check swap space - NEEDS MORE WORK.
* Set permissions so web server an create, update, and delete files in ${ALLSKY_CONFIG}.
* Renamed some variables, added comments so code is easier to read.
* Split whiptail messages into multiple lines so they are easier for developers to read and update.
> install.sh: fixes and cleanup

- install.sh
Move the lines that set permissions to before they are needed.
> install.sh: move permissions up

- install.sh
The "progress" lines shouldn't have any blank lines between them for consistency.
> install.sh: get rid of blank lines

- allsky.sh
- install.sh
> Installation improvements

- config_repo/config.sh.repo
- html/includes/createAllskyOptions.php
- install.sh
- scripts/makeChanges.sh
- variables.sh
Several bug fixes and other changes found during installation testing.
> Installation fixes and changes

- install.sh
Put all functionality in functions so main part of program can simply call the functions.  This makes it much easier to see what's happening.  It also makes it easy in the future to allow users to call only certain functions, e.g., to add swap space they might execute:   install.sh --swap
> install.sh: Major restructuring

- uninstall.sh
* Use whiptail
* Improve messages to user
* Let user run from anywere
> uninstall.sh: improve

- install.sh
* Fix full name of "version" file.
* Get rid of second "."
> install.sh: fix 2 bugs

- website/install.sh
* Moved most code into functions.
* Do one "display_msg" using ${MSG} instead of multiple calls.  It's easier to read this way.
> restructure

- install.sh
* Fix bug where program that needs PHP is called before PHP is installed on new systems.
* Completed code to check for swap space.
* Added ability to call each function separately.  Useful, for example, to only add swap space.
> install.sh: bug fix and additional work

- html/includes/authenticate.php
> use getVariableOrDefault()

- config_repo/options.json.repo
to be consistent with daytime name
> Rename Nighttime Brightness

- scripts/makeChanges.sh
The settings file doesn't always get made during installation for some reason
> makeChanges.sh: add error checks

- install.sh
Plus, 2nd DEBUG= should be DEBUG_ARG=
Plus, move FORCED_CREATING_SETTINGS_FILE to prior to when it's used.
> install.sh: bug fix: s/tmp/tmpfs/

- scripts/makeChanges.sh
Search for special string, not everything BUT that string.  Allow other things to be in the string, like debugging output.
Also, error out if there was NO output.
> makeChanges.sh: major bug fix

- html/includes/createAllskyOptions.php
Want level 1 to show creation/deletion of files.  Level 2 should be more verbose
> createAllskyOptions.php: change debug level

- scripts/saveImage.sh
If the first upload.sh fails, subsequent ones most likely will as well, so don't try them.
> saveImage.sh: only do upload.sh if prior one ok

- src/allsky_common.cpp
Wasn't updating cg->latitude and cg->longitude
> allsky_common.cpp: bug fix with lat/long

- html/includes/save_file.php
- scripts/upload.sh
Do better checking for upload errors.
> Improve saving files

- website/install.sh
Need to handle --update before moving the current website to allsky-OLD
> install.sh: bug fix: do update before moving

- scripts/functions.sh
They should look like:
*** ERROR:
**********
some message
**********
> functions.sh: put messages on separate lines

- scripts/postToMap.sh
- website/install.sh
Primarily for developers to be able to update/delete map entries of other people.
> postToMap.sh: add --machineid

- src/allsky_common.cpp
When N, S, E, W were used, the code wasn't setting latitude/longitude. This PR fixes that.
> allsky_common.cpp: bug fix lat/long

- html/index.php
The "X" in the close button was too low.  This centers it vertically.
> index.php: center close button X

- allsky.sh
- config_repo/config.sh.repo
- scripts/saveImage.sh
Determine if the mini-timelapse should be created and uploaded now, or wait.
> Allsky.sh complete implementation of mini timelapse

- scripts/upload.sh
* If null, use the basename of the file to upload
> upload.sh: allow empty destination file name

- scripts/upload.sh
Also use [[ instead of [ in a couple places
> upload.sh: improve error message

- scripts/functions.sh
- scripts/makeChanges.sh
- scripts/postData.sh
- scripts/postToMap.sh
Several scripts need to ensure the latitude and longitude are in 123.45[NSEW} format, so put that code in the convertLatLong() function in functions.sh.
> Add convertLatLong()

- install.sh
* Also, don't add "ERROR" to "display_msg error" since it already adds it.
> install.sh: Let user know if website is old

- install.sh
The message should only be displayed if the directory is actually moved.
> install.sh: move where message is displayed

- website/install.sh
* Make sure latitude and longitude are set (the script fails if they aren't), then use convertLatLong() to convert them to N, S, E, W format.
* Made determining COMPUTER slightly more efficient.
> install.sh: check lat/long & use convertLatLong()

- website/install.sh
* Bug fix: set WEBSITE VERSION before it's used.
* Enhancement: include WEBSITE VERSION in header.
* Fix indentation with "analyticsTracking.js".
* Bug fix: } in wrong place.
* Improved handling of prior websites
> fixes and enhancements

- scripts/saveImage.sh
* Only try to upload a mini-timelapse if we are saving images
> saveImage.sh: fix mini-timelapse bug

- src/capture_ZWO.cpp
* Cast the GC.lastMean to avoid bogus numbers in log output.
* Try to detect when ping-ponging (i.e., below target, then above, then below, then above...).  This doesn't work, but is a first try.
> capture_ZWO.cpp: misc fixes and changes

- config_repo/sudoers.repo
- install.sh
For a future addition to the WebUI letting people set the Pi's date to their browser's date.
> Add "date" to suudoers list

- html/includes/functions.php
file_exists() only works if you know the directory of the caller, which can be from ~/allsky, ~/allsky/scripts, or ~/allsky/html.  Check return of "include" instead.
> functions.php: improvement with $defs

- install.sh
Was looking for local Allsky Website configuration file but then using remote one.
> install.sh: Allsky Website repo fixes

- config_repo/configuration.json.repo
This better reflects that it's the sidebar on the left.
> configuration.json.repo: s/sidebar/leftSidebar

- config_repo/configuration.json.repo
to "Allsky Settings" to match what's displayed on the WebUI.
> configuration.json.repo: rename "Image Settings"

- scripts/saveImage.sh
Bug fix: The "geometry" argument to `convert` needs an `x` to separate the arguments, not `,`.
> Auto stretch bug fix

- scripts/makeChanges.sh
* Field name changed to "Allsky Settings".
* No need to post twilight data.
> makeChanges.sh: displaySettings changes

- README.md
> README.md: updates for AUTO_STRETCH

- config_repo/lighttpd.conf.repo
Remove trailing "/" from documentation alias.
> allow http://allsky/documentation

- documentation/documentation.js
so a tag is only processed once
> documentation.js: remove "allsky" attribute

- documentation/documentation.js
Cleanup all the debug statements now that it's working.
> documentation.js: cleanup

- html/index.php
* Rename to "Web User Interface".
* Remove messages file instead of truncating it.
> index.php: 2 minor changes

- allsky.sh
* The installation file is "installation_info.txt".
* Rename the variable as well.
* Add a WebUI message (an enhancement)
> allsky.sh: bug fix: change name of file

- README.md
- install.sh
- scripts/endOfDay.sh
- scripts/endOfDay_additionalSteps.repo
- scripts/endOfNight.sh
- src/capture_RPi.cpp
- src/capture_ZWO.cpp
Run a new endOfDay.sh script at the end of daylight.
This is similar to the endOfNight.sh script.
Some users have asked for this.
> Allow for end of day script

- html/includes/status_messages.php
$status doesn't exist, so can't use    $status .= xxx
Also convert spaces to tabs.
> status_messages.php: remove "."

- scripts/postData.sh
Check up front if there's no local and remote website. For the remote website, assume if there's a PROTOCOL that there's a remote server to copy files to.
> postData.sh: check if no website exists

- html/dist/css/custom.css
- html/includes/allskySettings.php
more improvements for small screens
> Allsky settings.php improved formatting

- scripts/makeChanges.sh
* Change DEBUG statements slightly and add some.
* Improve the way we determine if there's a local or remote website.
* BUG FIX: need to run postData.sh when camera type changes so a new settings file is uploaded.
* Don't display postData.sh output when camera type changes, since it adds unneeded messages.
> makeChanges.sh: misc changes and a bug fix

- documentation/basics/index.html
Needed to get links to work correctly on the GitHub page.
> index.html: add "allsky=true"

- .gitignore
Remove redundant enrties from the .gitignore file
> Fixes for gitignore

- documentation/documentation.js
> documentation.js: comment out test lines

- documentation/FAQ/index.html
- documentation/miscellaneous/nomenclature.html
- documentation/settings/allsky.html
Sure is a pain getting html files to work on the Pi AND in GitHub!
> Can't use "/documentation" in <link>

- documentation/sidebar.html
Can't use relative paths since this file is included into html files at different levels of the tree.
> sidebar.html: need /documentation in all URLs

- documentation/documentation.js
Also, fix description of the file and remove unneeded variable.
> documentation.js: add missing {

- documentation/documentation.js
Only add "/documentation/" if NOT in that directory.
> documentation.js: conditionally add string

- documentation/documentation.js
FINIALLY!!!!!!!
Got this darn thing working.
Pages and images can now be viewed on the Pi and on GitHub, regardless of what directory they are in.
> documentation.js: final cleanup

- documentation/documentation.js
Add some debugging statements to figure out why.
> documentation.js: local href not working

- website/install.sh
* Use [[ instead of [
* Rename ALLSKY_WEBSITE_OLD to more meaningful name.
> install.sh: minor changes

- website/install.sh
* Plus, use $ALLSKY_REMOTE_WEBSITE_CONFIGURATION_FILE instead of ${ALLSKY_CONFIG}/${ALLSKY_WEBSITE_CONFIGURATION_NAME}
> install.sh: use local configuration file

- html/includes/functions.php
The old way didn't work during installation
> functions.php: fix including allskyDefines.inc

- html/documentation/css/documentation.css
Styling changes for tables and blockquotes
> Styling changes for tables and blockquotes

- html/documentation/explanations/keograms.html
Needed for when viewing documentation on GitHub
> keograms.html: bug fix: need lazy loading

- scripts/functions.sh
The documentation will tell people to run this to determine their sunrise and sunset times.
> functions.sh: add get_sunrise_sunset()

- html/documentation/css/documentation.css
* Make a couple things variables.
* Simplified grid - just 2 columns.
* Got rid of a bunch of stuff we don't use, e.g., flex.
* Changed many attributes to make things look nicer.
* Added classes for table of contents header and file names.
> documentation.css: greatly simplified

- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/include/allsky_common.h
Don't display the mode mean arguments if they aren't supported.
> Add supportsMyModeMean

- html/documentation/basics/Linux.html
- html/documentation/basics/Pi.html
- html/documentation/css/documentation.css
- html/documentation/explanations/angleSunriseSunset.html
- html/documentation/explanations/constellationOverlay.html
- html/documentation/explanations/darkFrames.html
- html/documentation/explanations/imageOverlays.html
- html/documentation/explanations/keograms.html
- html/documentation/explanations/startrails.html
- html/documentation/installations/Allsky.html
- html/documentation/installations/AllskyWebsite.html
- html/documentation/miscellaneous/FAQ.html
- html/documentation/miscellaneous/nomenclature.html
- html/documentation/settings/EditorColors.html
- html/documentation/settings/allsky.html
- html/documentation/settings/allskyWebsite.html
- html/documentation/sidebar.html
Added a couple classes and modified documentation pages to use them.
Also use the new way to automatically hide the sidebar on small screens.
> Documentation add web UI value class

- html/documentation/settings/allsky.html
* Use local copy of font awesome
* remove <hr class="separator"> since they are not needed
* Added missing </details>
> allsky.html: misc changes

- html/documentation/js/documentation.js
This will eventually replace the one in "documentation" once all the other files are modified.
> Add documentation.js to "documentation/js" folder

- src/capture_ZWO.cpp
* Improve debug output.
* BUG FIX: Don't let next exposure exceed max exposure.
* BUG FIX: Avoid a divide by zero error.
* Typecast gain passed to setControl().
> capture_ZWO.cpp: misc fixes

- install.sh
* Remove the two log files - normally not needed except for testing.
* BUG FIX: Can't "source" the old config.sh file since the settings file hasn't been created, and "source" will fail.
* Add a "recheck_swap" function that the documentation will tell users to execute to update swap.
* Improve messages in check_swap() function.
* umount the old allsky/tmp if it was mounted.
* BUG FIX: Check for /var/www/html directory that doesn't contain an old WebUI.
* For users with new-style prior versions, give them a possible shortcut to moving configuration settings from old to new.
* Don't display the "Welcome to the installer" message when running a function, since from a user's perspective they aren't installing Allsky.
* Always generate the "Use Allsky Settings link to configure Allsky" image.
> install.sh: several fixes and improvements

- install.sh
Always check if there's an old WebUI directory (/var/www/html), and whether or not it's valid. Do this even if there's an old website in ~/allsky/html/allsky.
> install.sh: always check for old WebUI

- html/index.php
We no longer edit .js files, so no need to include the codeMirror file for them.
> index.php: no longer need javascript.js

- html/includes/functions.php
* Handle "false" booleans.
* Handle empty strings.
* Handle null values
> functions.php: improve getVariableOrDefault

- html/includes/allskySettings.php
- html/index.php
The Allsky Settings page handles camera settings as well as other settings, so "camera_conf" is a somewhat misleading name.
> WebUI rename: camera_conf

- html/documentation/sidebar.html
Can combine two <div>'s into one.
> sidebar.html: one less <div>

- website/install.sh
* Use temporary variable instead of duplicating directory names, to aid in maintenance.
* Fixed issue of not creating "myImages" directory.
* Refer to documentation instead of Wiki.
* Slight wording changes.
> install.sh: several minor changes

- html/includes/admin.php
- html/includes/allskySettings.php
- html/includes/createAllskyOptions.php
- html/includes/editor.php
- html/includes/functions.php
- html/includes/save_file.php
Need to handle multiple lines from save_file.php - the status line (success or error) as well as debug lines.  The debug lines need to go to console.log().
> Tell update file() if it should write to console.log

- html/includes/images.php
> images.php: remove obsolete variable

- install.sh
> install.sh: restore missing -R

- install.sh
> Add missing dependencies for headless operation

- scripts/functions.sh
The second message will be un-colored.
> functions.sh: allow optional 2nd message

- install.sh
> Install.sh make more user friendly

- allsky.sh
- scripts/generateForDay.sh
- scripts/makeChanges.sh
- src/Makefile
Put the capture_*, keograms, startrails, and sunwait commands in ~/allsky/bin to help keep ~/allsky clean.
> Put binaries in allsky/bin

- allsky.sh
- install.sh
Create an "image.jpg" file at the beginning of installation that says "installation in progress".
Create a different one if installation fails.
> Better post installation message

- html/index.php
Not sure which of the added lines fixes it, but it used to remove the file but not refresh the page, so the message was still there.
> index.php: fix clearing messages

- html/js/overlay/fields/oe-text.js
- html/js/overlay/oe-uimanager.js
- scripts/modules/allsky_overlay.py
Fix a few issues 
- internationalisation issues with int function
- Changing font size would cause the snap rectangle to be in the wrong position
> Fix overlay issues

- html/js/overlay/oe-uimanager.js
Enable the toolbar 'save' button as soon as a change is made, previously the user would have to click off of the field which is not a good user experience
> UI change to enable save button withouy having to click off of the field

- config_repo/options.json.repo
- src/allsky_common.cpp
- src/capture_RPi.cpp
- src/capture_ZWO.cpp
- src/include/allsky_common.h
Rename "External Overlay" to "Overlay Method" in the WebUI and other appropriate places.
> Rename setting to options.json.repo

- scripts/modules/allsky_overlay.py
> Fix internationlisation issues

- html/js/jqPropertyGrid/jqPropertyGrid.js
- html/js/overlay/oe-uimanager.js
Couple of changes to improve the UI
- Input fields in the property editor now update the overlay in real time
- The overlay tab title contains an indicator if the overlay has been modified
> Improve overlay UI

- html/js/overlay/fields/oe-text.js
Ensure all fields in the property editor mark the overlay as dirty
> UI improvements

- scripts/modules/allsky_overlay.py
Fix for spaces in text based extra data files
> Fix for spaces in text based extra data files

- scripts/postToMap.sh
> Post to map.sh bug fix s/M/E

- scripts/check_allsky.sh
* Change message when new version is found.
* Use checkPixelValue in a couple more places.
> check_allsky.sh: minor changes

- html/includes/allskySettings.php
- html/index.php
- website/install.sh
In the next release we'll display the settings in a WebUI-like format.  This PR prepares for that.
> Allow read only settings page

- scripts/modules/allsky_overlay.py
- Also added RA and DEC as fields for the planets
> Fix for planets when observer is in the eastern hemisphere

- html/documentation/css/custom.css
> custom.css: add missing class

- scripts/modules/allsky_overlay.py
Fix for DNS issues with Skyfield and NASA
> Fix for DNS issues with NASA

- html/index.php
* Force some pages to be refreshed by adding a timestamp to their URL.  These are any pages that gather information that may have changed since the last visit.
* Rename some of the page for more descriptive titles and to slightly shorten them.
* Fix indentation of several lines
> index.php: force refresh plus others

- scripts/postData.sh
* All remote files go in IMAGE_DIR (data.json) or a directory within IMAGE_DIR.  That wasn't working.
* Also fix typo in --settingsDir
> upload remote files relative to IMAGE_DIR

- html/includes/allskySettings.php
Add a timestamp to the URL when updating the page, similar to what index.php does.
> allskySettings.php: force refresh after update

- scripts/check_allsky.sh
* Fixed a problem with a couple variables not being checked correctly.
* Added several more PROTOCOL-related checks.
> check_allsky.sh: fix and add to PROTOCOL checks

- .github/workflows/ci_shellcheck.yml
- scripts/addMessage.sh
- scripts/check_allsky.sh
- scripts/copy_notification_image.sh
- scripts/darkCapture.sh
- scripts/darkSubtract.sh
- scripts/endOfDay.sh
- scripts/endOfNight.sh
- scripts/functions.sh
- scripts/generateForDay.sh
- scripts/generate_notification_images.sh
- scripts/makeChanges.sh
- scripts/periodic.sh
- scripts/postData.sh
- scripts/reload.sh
- scripts/removeBadImages.sh
- scripts/saveImage.sh
- scripts/timelapse.sh
- scripts/updateWebsiteConfig.sh
- scripts/upload.sh
Lots of small shellcheck changes so all bash scripts pass.
> Lots of shellcheck changes

- allsky.sh
Create extra directory when allsky starts
> Create extra directory

- install.sh
See individual commits for details.
> Install.sh handle prior items better, and more

- install.sh
- scripts/functions.sh
- scripts/makeChanges.sh
- scripts/postData.sh
- scripts/updateWebsiteConfig.sh
* get_variable() was used in multiple places so centralize it.
* Add whatWebsites() to functions.sh so scripts can determine if a local, remote, both, or none Websites exist.
> Add get_variable() and whatWebsites()

- scripts/upload.sh
* Fix bug with incrementing NUM_CHECKS - it caused the loop to never end.
* Add timeout on DNS resolution.
* Add a couple DEBUG statements.
> upload.sh: fix bug, timeout on DNS

- scripts/postData.sh
To aid in debugging, if --debug was specified for postData.sh, pass it to upload.sh.
> postData.sh: pass DEBUG to upload.sh

- html/documentation/installations/Allsky.html
- install.sh
Copy rather than move overlay/module files
Add allskyperiodic service to upgrade notes
> Fix for overlay and modules when upgrading

- install.sh
Change move command to copy for all files except images and darks when upgrading
> Change move commands to copy commands 

- scripts/postToMap.sh
* Put quotes around true and false
* use == instead of =
* Exit if unable to "source"
> postToMap.sh: minor cleanup

- html/includes/configureWiFi.php
* Allow Open SSIDs to be added.
* Display a "title" message for disabled Update and Delete buttons.
* Display the passphrase if hovered over "*******" version.
> configureWiFi.php: better messages, more

- html/documentation/troubleshooting/uploads.html
* Mention LFTP_PASSWORD.
* Use new location for lftp command files (~/allsky/tmp/lftp_cmds).
> uploads.html minor fixes

- scripts/upload.sh
* For every protocol, only create the output log file if there's an error.  This saves writes.
* When in DEBUG mode, put the REMOTE_PASSWORD in the lftp_cmds file to aid in debugging
* Misc style and minor wording changes.
> upload.sh improvements

- config_repo/Makefile
- config_repo/allsky.service.repo
- config_repo/allskyperiodic.service.repo
* Use ${ALLSKY_SCRIPTS} in service repo files.
> Use ALLSKY_SCRIPTS in repo files

- allsky.sh
* Compare numeric arguments as numbers.
* Always create $ALLSKY_ABORTEDUPLOADS
* Misc style changes.
* Don't put debuglevel in config file since it's already on command line.
> allsky.sh: misc minor changes

- scripts/flow-runner.py
- scripts/periodic.sh
Every 5 seconds the periodic code runs and if ALLSKY_DEBUG_LEVEL is >= 1, two messages are added to the log. If any work actually takes place, additional log entries are added for log levels 3 and 4.
> Update flow-runner.py: change log level

- src/capture_RPi.cpp
Also, split a comment and shortened a ----- comment to not wrap on my window.
> capture_RPi.cpp: don't use exif yet

- html/documentation/css/documentation.css
- html/documentation/overlays/overlays.html
> Overlays.html formatting and add details

- src/allsky_common.cpp
- src/capture_RPi.cpp
- src/capture_ZWO.cpp
- src/include/allsky_common.h
These messages will appear in the WebUI.
In the next release we'll need to make the messages more user-friendly and describe what should be done.
> Add System Messages on errors and warnings

- html/documentation/troubleshooting/AllskyWebsite.html
* Remove references to POST_END_OF_NIGHT, which no longer exists.
* Improve solutions for "postData.sh" and "no thumbnail" problems.
> AllskyWebsite.html: remove POST_END_OF_NIGHT

- scripts/generateForDay.sh
* People with older Allsky Websites will often have timelapse video thumbnails that say "No thumbnail".  There's a new setting that will fix that for future videos, but to make it easy for the user to fix <existing> missing thumbnails, add a "--thumbnail-only" option.  This will create or upload only video thumbnails, not the video file.
> generateForDay.sh: add THUMBNAIL_ONLY

- scripts/functions.sh
- scripts/postData.sh
Upon encountering errors, use addMessage.sh put add them to the system errors in the WebUI.
> postData.sh: use addMessage.sh

- html/documentation/troubleshooting/RPiCameras.html
- html/documentation/troubleshooting/other.html
Move this fix from "other.html" to "RPIcameras.html" where it belongs.
> Move fix for "RPi HD camera stopped working"

- html/index.php
In order for the WebUI to refresh the page after clearing the system message, we need to add a timestamp to the URL.
> index.php: add timestamp

- src/allsky_common.cpp
> allsky_common.cpp: remove " ***"

- html/includes/allskySettings.php
It looks nicer and is easier to see.
> allskySettings.php: add space

- allsky.sh
extraArgs is already in the settings file so we don't need to add it separately.
> allsky.sh: add debuglevel and remove extraargs

- html/js/overlay/oe-uimanager.js
Fix for snap rectangle being in the wrong place when a field label is changed
> Fix for snaprectangle

- html/public.php
Fixes image source on public.php
> Fix broken image source on public.php

- install.sh
"set_webserver_permissions" was the old name for "set_permissions".
> install.sh bugfix: set_webserver_permissions

- install.sh
Ooops, missing an occurrence of set_website_permissions
> Install.sh bug fix set_webite_permissions

- scripts/functions.sh
* If a direction is specified, make sure latitude contains N or S.
* If a direction is specified, make sure longitude contains E or W.
* On error, let the user know what they entered.
> functions.sh: improve latitude/longitude checks

- scripts/check_allsky.sh
See individual commits for details.
> Check allsky.sh improvements and additions

- install.sh
* Add some DEBUG statements.
* BUG FIX: remove "z" that was added for testing.
* Remove unneeded exports.
> install.sh: slight locale improvements

- html/includes/allskySettings.php
- html/includes/createAllskyOptions.php
- html/includes/functions.php
- html/index.php
There are several places in the code where a json file is opened and then decoded.  Most of those places didn't do any error checking, so if the json file was corrupted, the web page did wierd things.
The PR adds a get_decoded_json_file() function to read the file and decode it, while checking for errors.
> Functions.php add get_decoded_json_file()

- config_repo/Makefile
- install.sh
- Removed directory copy from Makefile and added to install.sh
- Moved default overlay copy to slightly later in the install process
> Move module and overlay install to install.sh

- install.sh
Also fix typo in "Got usage message..." line.
> install.sh: check for no locales

- install.sh
Forgot to remove the "x" from "xINSTALLED_LOCALS" I had in to test the error code.
> install.sh: remove testing character

- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/capture_RPi.cpp
- src/include/allsky_common.h
* width and height were reversed for Module 3 camera
* Added code to support multiple cameras.  This shouldn't impact cases where there is only one (99.999999% of the time).
> Capture_RPi.cpp bug fixes with width and height

- src/allsky_common.cpp
- src/capture_RPi.cpp
* Fixed segmentation fault due to char[ ] variable not being big enough to fit string being copied to it (it used strcpy()).
* As a result of that fix, removed the debugging "Got here" lines.
* Improved signal handling so it doesn't report it received a signal twice.
* Other minor changes.
> capture_RPi.cpp: fixes and changes

- install.sh
- scripts/flowupgrade.py
Adds an script to update module setting during an allsky upgrade
pi@allskydev:~/allsky/scripts $ ./flowupgrade.py  -h
usage: flowupgrade.py [-h] --prior PRIOR --config CONFIG [-d DEBUG]
optional arguments:
-h, --help            show this help message and exit
required arguments:
--prior PRIOR         Prior folder containing configs
--config CONFIG       Allsky config folder
optional arguments:
-d DEBUG, --debug DEBUG
> Add module updater script

- config_repo/config.sh.repo
* If SETTINGS_FILE isn't defined, print an error message and return 1.
* Include ${ME2} in messages (don't use ${ME} in case the program including config.sh has it set).
> config.sh.repo: add SETTINGS_FILE check

- html/documentation/css/custom.css
- html/documentation/css/documentation.css
- html/includes/system.php
Allow fields in the WEBUI_DATA_FILES files to be separated by multiple table, to make it easier to line them up with optional column headers.
> system.php: Allow multiple tabs, add classes

- html/includes/status_messages.php
* isMessage() returns true if there's at least one status message.  This allows the caller to not output "<p>messages</p>" if there aren't any messages.
* Also, only output "<table>" and "</table>" if there were any messages.
> status_messages.php: add isMessage()

- html/includes/system.php
* Make all error messages appear together - this requires displayUserData() to return an error message.
* Use systemPageAdditionsLineType and errorMsg classes.
* Fix bug checking for blank lines (need to also check for "\n").
* Output a javascript console message when executing a command, for debugging.
* Use the $status->isMessage() function to determine whether or not to display messages.
> system.php: Improve WEBUI_DATA_FILES code

- html/includes/admin.php
- html/includes/configureWiFi.php
- html/includes/dashboard_LAN.php
- html/includes/dashboard_WLAN.php
- html/includes/dhcp.php
- html/includes/editor.php
- html/includes/hostapd.php
- html/includes/liveview.php
- html/includes/status_messages.php
Check if there are any status messages to display before calling the routine to display them.
Usually the invoker surrounds messages with "<p>messages</p>".  Using $status->isMessage() avoids outputing "<p></p>" when there are no messages.
> Web UI use $status->isMessage()

- html/documentation/css/custom.css
- html/includes/liveview.php
When clicking on the liveview image, it becomes full-screen.
Let the user know, by adding a title and a pointer cursor.
> Liveview.php indicate image is clickable

- html/documentation/installations/AllskyWebsite.html
Improve text by clarifying items and adding instructions.
> AllskyWebsite.html: many small improvements

- html/documentation/css/documentation.css
Make the sidebar slightly narrower to fit more on page.
> documentation.css: decrease padding

- config_repo/config.sh.repo
This will allow it to be used in overlays, along with CAMERA_TYPE.
> config.sh.repo: add CAMERA_MODEL

- html/includes/overlay.php
* Minor wording changes.
* Add $displayMaskTab to determine if exposure mask tab should display or not - makes it easy to turn on and off.
> overlay.php: restore changes

- scripts/endOfNight.sh
On slower machines like Pi Zero 2, when the end of night script is running, it significantly slows down image processing, which can cause many images to back up and running allsky/tmp out of space.
> endOfNight.sh: Add $NICE

- html/documentation/explanations/angleSunriseSunset.html
- scripts/functions.sh
The documentation calls the periods "daytime" and "nighttime", not "sunrise" and "sunset", so be consistent with the documentation.
> functions.sh: change column names

- upgrade.sh
Add initial version of upgrade.sh.
This script will be updated and made usable in the next release.
> Add upgrade.sh

- install.sh
* Remove redundant "from".
* Update version check to current dev version.
* SETTINGS_FILE_NAME doesn't exist anymore so determine it at runtime.
> install.sh: update version

- config_repo/overlay/config/fields.json
Also, convert the SUN_* variables that return a date-time to "Date" which then allows formatting.
> fields.json: add formats and samples

- config_repo/lighttpd.conf.repo
* Put all server.modules  items in same place.
* Move alias.url line up before the one on line 23 that added to the list.
> lighttpd.conf.repo: slight mods

- src/capture_RPi.cpp
* Don't duplicate messages when a signal is received.
* Check for error with WIFEXITED().
> capture_RPi.cpp: handle errors better

- scripts/functions.sh
The second column is the START of nighttime, not the end.
> functions.sh: s/end/start

- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/capture_RPi.cpp
- src/capture_ZWO.cpp
- src/include/allsky_common.h
First step toward removing "locale" from the WebUI.
> Remove  locale option

- scripts/modules/allsky_overlay.py
* Use new variable ${ALLSKY_EXTRA} to make it easy to move the "extra" directory.
* Support formatting for Bool types.
* Minor changes in comments.
* More user-friendly invalid formatting messages.
> allsky_overlay.py: several changes

- html/cgi-bin/format.py
Also remove unnecessary spaces.
> format.py: support Bool formats

- html/includes/overlay.php
- html/includes/overlay_sample.py
- scripts/modules/allsky_overlay.py
* More adding Bool type.
* Allow user to define Bool types.
* Allow user to format Bool type for Yes/No, On/Off, True/False, 1/0.
* Allow multiple "empty" fields.
> Add Bool type

- scripts/modules/allsky_overlay.py
If a variable has no msg type, use "???" for it's value (to distinguish from "??" which means there is no value.
> allsky_overlay.py: display "no variable type" msg

- html/documentation/overlays/overlays.html
* Expand on meaning of "variable" and "expire" field.
* Several minor wording changes.
> overlays.html: changes # 3

- install.sh
Also, add/improve a couple comments.
> install.sh: set ALLSKY_VERSION

- install.sh
Bad coding practice to use a global variable.
> pass prompt to prompt_for_lat_long()

- install.sh
Also change "-y" to "--assume-yes" for people not familiar with apt-get.
> install.sh: combine apt-get install's

- install.sh
Installation of the dependencies took over an hour for one of the testers with a Pi 4 (!)
> install.sh: update execution time

- scripts/endOfNight.sh
Need to pass "--nice 15" to programs on command line, PLUS run flow-runner.py using "nice -n 15 flow-runner.py".
> endOfNight.sh: Add NICE_ARG

- config_repo/config.sh.repo
- html/documentation/settings/allsky.html
- scripts/check_allsky.sh
- scripts/endOfNight.sh
- scripts/postToMap.sh
To be consistent with other settings, "0" now disables the DAYS_TO_KEEP and WEB_DAYS_TO_KEEP settings.
This PR modifies all the scripts that deal with those settings.
Also improved the handling of WEB_DAYS_TO_KEEP in endOfNight.sh.
> Allow 0 for *DAYS_TO_KEEP

- install.sh
- variables.sh
This allows us to check if it's still there an remind the user.
> Put PRIOR_ALLSKY_DIR in variables.sh

- html/includes/status_messages.php
- scripts/addMessage.sh
Allow newlines in System Messages, and replace them with <br>.
> Handle newlines in system messages

- scripts/postData.sh
Minor changes that don't impact functionality but make the code slightly easier to maintain.
> postData.sh simpler error handling

- website/install.sh
* If the user only has a remote Website, they'd get an error when running "install.sh --remote" because the check for data.json was looking for the LOCAL version.
* Added another check prior to running remote code.
* Now do remote check earlier.
* Always remove the temporary test upload file.
> install.sh: bug fix and improvements

- scripts/upload.sh
This also does at least two checks for all files.
> upload.sh: simplify "other upload" check

- scripts/upload.sh
It was displaying the NUM_CHECKS that was already incremented.
> upload.sh: bug fix with NUM_CHECKS

- install.sh
- scripts/installUpgradeFunctions.sh
Add some debugging and logging statements for troubleshooting.
More will be added in a future PR.
> Install.sh add debug message

- scripts/upload.sh
SEVERITY was being used before it was defined.
> upload.sh: fix messages

- allsky.sh
- scripts/timelapse.sh
- variables.sh
Only allow one mini-timelapse creation at a time - any new one will abort.
> Only allow one mini timelapse creation at a time

- html/includes/allskySettings.php
* Allows fields to exist in the settings file that aren't displayed but should remain there when other settings are updated. This is done by passing the value as a "hidden" variable.
* In the error messages at the top, list more details, like the required fields that are empty.
* To help troubleshoot, output "\n\t" on lines so they appear on separate lines in HTML output.
> allskySettings.php: handle not displayed settings

- allsky.sh
- scripts/copy_notification_image.sh
- scripts/endOfDay.sh
- scripts/endOfNight.sh
- scripts/functions.sh
- scripts/generateForDay.sh
- scripts/makeChanges.sh
- scripts/periodic.sh
- scripts/postData.sh
- scripts/postToMap.sh
- scripts/removeBadImages.sh
- scripts/saveImage.sh
- scripts/timelapse.sh
- scripts/updateWebsiteConfig.sh
- scripts/upload.sh
Move the settings() function from config.sh to functions.sh.
This required that all files that "source config.sh" first "source functions.sh" since config.sh uses the settings() function.
> Move settings() function

- html/documentation/settings/allsky.html
Warn if there are mini timelapse creations that fail because another one is still running.
> allsky.html: warn about mini timelapse

- config_repo/config.sh.repo
> config.sh.repo: remove return 0

- config_repo/config.sh.repo
> config.sh.repo: remove settings()

- install.sh
* Updated PRIOR_ALLSKY_VERSION value
* Remove reference to overlay_sample.py which no longer exists.
* Replaced some debug "echo" statments with "display_msg debug"
* Use "get_version()" instead of hard-coded ".../version".
* If the prior Allsky version is being used, get its CAMERA_TYPE.
* Bug fix: replace the ALLSKY_VERSION in config files that don't have "XX_ALLSKY_VERSION_XX" which will be the case when upgrading.
* Check for missing settings file.
* Don't call get_lat_long() (which needs the settings file) if the prior settings file is missing, in which case the new settings file will not be there either.
* Bug fix: CONFIG_SH_VERSION was used before set.
* Move call to update_config_sh() until after final config.sh file is in place.
* Remove "source config.sh" since it's not needed. …
> install.sh: a few bug fixes, plus improvements

- html/index.php
TODO: read the "messages.txt" file using ajax ever page refresh, then every x seconds after that to catch updates, rather than having to add a timestamp to every url.
> index.php: add more timestamps

- html/index.php
* Bug fix: "filemtime" returns "false" or the time, not true.
* Produce better message when messages file changed.
* Bug fix: having timestamp in hidden variable doesn't work; add it to URL.
> index.php: bug fix + enhancement

- allsky.sh
- install.sh
- variables.sh
Don't put in allsky/tmp since it goes away after reboot and is cleared out during installation.
> Move installation_log directory

- html/includes/allskySettings.php
- install.sh
- scripts/makeChanges.sh
Pass the OLD_VALUE to makeChanges.sh.  This is needed so it can correctly update the overlay.json files when the camera type changes.
> Pass prior camera type to make changes.sh

- allsky.sh
- install.sh
- variables.sh
install.sh and allsky.sh use it, so put it in variables.sh.
Remind the user the directory still exists so they can delete it when no longer needed.
> Install.sh use ALLSKY_INSTALLATION_LOGS

- install.sh
Also, use ALLSKY_OVERLAY and update the ALLSKY_VERSION variable in config.sh.
> install.sh: add more logging

- install.sh
Also, replace "jq -r" with "settings".
> install.sh: add even more logging

- install.sh
> install.sh: remove "total_mem=" from RAM_SIZE

- install.sh
The local and remote configuration.json files (if the Website is installed) need their .config.AllskyVersion setting updated when updating Allsky.
> install.sh: add checks

- install.sh
Also:
* Create update_locale() to make .locale update since it's called from multiple places.
* Add log entries.
* Minor comment and indentation changes.
> install.sh: add .locale to settings file

- install.sh
* Display message when CAMERA_TYPE or CAMERA are not defined in a prior config file.  This "shouldn't" happen.
* Display message when CAMERA_TYPE or ALLSKY_VERSION aren't defined in update_config().  They should be, but they may not have been for one tester.
> install.sh: add log messages

- install.sh
* Fix a bug with checking version number of prior ftp-settings.sh.
* Add more log output.
* Other misc. changes
> Install.sh bug fix plus more

- scripts/postData.sh
This requires adding an optional "--websites w" argument to specify whether a local, remote, or both Websites should receive the files.
> postData.sh: allow doing local or remote only

- scripts/postData.sh
If a valid Website type was specified on the command line then set WEBSITES to that type.
> postData.sh: bug fix: set WEBSITES

- scripts/postData.sh
There's already a variable defined for the name of the directory, so use it.
> use ALLSKY_WEBSITE_VIEWSETTINGS_DIRECTORY_NAME

- install.sh
- scripts/makeChanges.sh
Bug fix:  Need to create the default overlay.json file since makeChanges.sh (which normally creates it) couldn't do it since the camera-specific file didn't exist when it was called.
Put the "Testers..." message in an "if" statement since the code will stay in the future, although the words will change.
> Installation bug fix plus more

- scripts/makeChanges.sh
Need to preserve the permissions of the overlay.json file.
> makeChanges.sh: preserve permissions

- html/includes/allskySettings.php
If a setting is empty, use its default if there is one, and warn the user to press the "Save changes" button.
> allskySettings.php: Use default value if not set

- scripts/removeBadImages.sh
The "convert" command can return a mean with a "e-" format and bc doesn't handle that.
> removeBadImages.sh: handle exponential means

- website/install.sh
$BRANCH doesn't exist yet so use $USER_SPECIFIED_BRANCH in error message.
> install.sh: minor bug with BRANCH

- website/install.sh
Add some checks for empty variables and log if needed.
> website/install.sh: add more log entries

- install.sh
I forgot to turn off the message to testers
> Install.sh: take out of testing

- scripts/upload.sh
And only display non-error output from PWD
> upload.sh: only run PWD once

- install.sh
- scripts/functions.sh
- scripts/installUpgradeFunctions.sh
- scripts/makeChanges.sh
Check early in the installation process if a camera is connected.
makeChanges.sh does a better job checking as well.
> install.sh handle no RPi camera better

- scripts/upload.sh
* Add "/" between REMOTE_DIR and DESTINATION_NAME.
* Remove "/" between BUCKET and REMOTE__DIR.
* Change DEBUG_LEVEL of one statement
> upload.sh: "/" changes

- html/documentation/changeLog.html
* Use REMOTE_USER
* Use DESTINATION_NAME
> Update changeLog.html: add 2 bug fixes

- html/documentation/css/documentation.css
These are duplicated from custom.css.
Eventually I'll merge those two files.
> Update documentation.css: add advanced-related classes

- html/documentation/css/custom.css
- html/includes/allskySettings.php
- html/index.php
Keep the buttons on the "Settings" page at the top of the screen, even when the user scrolls.
Add a "Top" button to make it easy to get back to the top.
> Keep "Save changes" and other buttons at top of screen

- html/includes/allskySettings.php
Set when Refreshing the Camera Type
> Update allskySettings.php: bug fix: set newValue to oldValue

- html/documentation/overlays/overlays.html
Add notes related to font uploads and php file upload limits
> Update overlay docs

- html/js/overlay/oe-uimanager.js
- scripts/modules/allsky_overlay.py
Ensure the last variable added has the correct index
> Fix for adding variables to the variable list

- config_repo/config.sh.repo
Comments on the lines breaks get_variable()
> Update config.sh.repo: remove comments from variable assignment lines

- config_repo/requirements-buster.txt
- config_repo/requirements.txt
Restore opencv back to full version to prevent upgrade issues
> Revert back to full opencv

- html/documentation/changeLog.html
- src/Makefile
- src/sunwait.patch
I thought it wasn't used, but it is, so need to add it back in.
> Add sunwait back in

- html/documentation/changeLog.html
- install.sh
This resolves Discussion #2578
> Only prompt for new hostname if it's currently "raspberrypi"

- src/ASI_functions.cpp
> ASI_functions.cpp: remove unneeded comments, support IMX290 sensor

- config_repo/lighttpd.conf.repo
- html/includes/editor.php
Add a use a "/config/" alias to point to allsky/config so the WebUI can more easily find config files.
This will also allow us to change the "/current/" alias to allsky/tmp so the local configuration.json can use "/current/image.jpg".
> Add "/config/" alias to web UI

- html/includes/functions.php
Also, add the interface name to status messages in case there are multiple interfaces.
> functions.php fix: don't assume $result[1] exists

- install.sh
- scripts/functions.sh
Centralizes updating a json file
> New update_json_file() function

- install.sh
* Get convert_settings() working for v2022.03.01.
* Fix broken prior settings file links.
* Rename PRIOR_ALLSKY values to "newStyle" and "oldStyle".
* Get the prior camera type from the prior settings file if it's a "newStyle" file.
* Several indentation changes to make things easier to read.
* Display settings file list in a couple other places for debugging.
> install.sh: get convert_settings() working, plus more

- allsky.sh
- html/includes/allskySettings.php
- html/includes/functions.php
- install.sh
- scripts/check_allsky.sh
- scripts/functions.sh
- scripts/installUpgradeFunctions.sh
- variables.sh
The installation knows when a reboot is needed and can indicate that to allsky.sh so it won't allow Allsky to start
> Determine if user rebooted after installation

- allsky.sh
- scripts/functions.sh
Make sure the log file always says why Allsky is stopping, even if there's a system message and/or a notification image.
> Improved "allsky stopped" messages

- install.sh
- scripts/functions.sh
- variables.sh
ALLSKY_REBOOT_NEEDED describes better what the file is for.
> Rename ALLSKY_UPTIME_SINCE to ALLSKY_REBOOT_NEEDED

- install.sh
This makes it easier to see if there are problems.
> Install.sh better log messages

- install.sh
Also, increase the size of a whiptail box so the question is visible.
> install.sh: add a couple log entries

- allsky.sh
- install.sh
- scripts/functions.sh
Took the code from install.sh that converted json to "FIELD <tab> VALUE" and put in a function (and also fixed a bug with it).
Changed allsky.sh to also use that function to speed up startup by about 10 seconds.
> Install.sh use convert_json_to_tabs

- scripts/functions.sh
If first word in the FIELD is "if" then it should not have a period.
> settings() bug fix

- install.sh
Currently no reboot is needed if going from v2023.05.01* to v2023.05.01*
> Update install.sh: add is_reboot_needed()

- src/capture_RPi.cpp
- src/include/mode_mean.h
- src/mode_mean.cpp
Unfortunately the mask used to determine the mean doesn't work.
Will need to get it working via a separate PR.
> capture_RPi: use lastMeanFull

- html/documentation/css/custom.css
- html/includes/liveview.php
* Convert a "style=" to a class.
* Remove unnecessary margin at the bottom of the image.
* Center the "X" button better.
> Minor tweaks to liveview

- config_repo/options.json.repo
> Update options.json.repo: remove "generic" from many items

- html/js/overlay/oe-uimanager.js
Fixes
1) Prevent fields moving on screen when the text is changed
2) Ensure the snap rectangle is aligned correctly
3) Fixes for when the grid is disabled
> Fixes for #2837

- allsky.sh
capture_RPi needs to know if very early, before processing other arguments, so it looks for it in argv[1].
> Update allsky.sh: Pass "-cmd xxx" on command line

- html/documentation/settings/allskyWebsite.html
Missing leading double quote.
Fixes Issue #2876
> Update allskyWebsite.html: Fix typo in URL

- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/include/allsky_common.h
Try to close the ZWO camera when done, in the hopes it will help resolve weirdness like ASI_ERROR_TIMEOUTs.
Some changes from point release 3 are also included since they were on my Pi.
> Use closeCamera()

- scripts/modules/allsky_overlay.py
Removes the error message that displayed when there is an issue with the colour
This is a temporary fix until I can find out whats still causing this.
> Hotfix to remove colour error

- scripts/modules/allsky_clearsky.py
I've added new param mqttusetls to allsky_clearsky.py module. Not everyone is using MQTT with TLS, so I wanted to make it configurable.
> Add mqttusetls param to allsky_clearsky.py

- scripts/modules/allsky_meteor.py
Added new config options and functionalities to:
1. Save meteor detection log to separate text log file
2. Save an intermediate images with detected meteors to separate folder
> Added saving results of metors detections

- scripts/modules/allsky_saveintermediateimage.py
- scripts/modules/allsky_shared.py
Added possibility to use custom filename for output image
> Updated allsky_saveintermediateimage.py module - custom filename

- install.sh
* Mention Bookworm Pi OS being released in October 2023.
> Update install.sh: add log_info() and others

- html/allsky/virtualsky/virtualsky.js
Bug fix for portable devices - this disables rotation of constellation by touch and drag when rotation is disabled.
Fix provided by @Mr-Grouch
> Update virtualsky.js: bug fix with s.mouse

- scripts/modules/allsky_starcount.py
- Added possibility to use custom star template image
- If debug is enabled - annotate only on debug images
- fixed rounding to integer (s.int is for strings, not pure float numbers and throws exceptions when used on floats)
> Starcount - added possibility to use custom star template

- install.sh
> Update install.sh: add check for prior python install

- variables.sh
> Update variables.sh: Add PI_OS

- allsky.sh
- scripts/installUpgradeFunctions.sh
> Update installUpgradeFunctions.sh: don't set ALLSKY_VERSION

- html/index.php
- scripts/saveImage.sh
> Update saveImage.sh: fix: remove arguments

- scripts/upload.sh
Also, make sure 'gsutil' is found.
> Upload.sh fix use DESTINATION_NAME for gcs

- config_repo/options.json.repo
The user can't change it and it only confuses things
> Update options.json.repo: don't show Camera Model

- config_repo/options.json.repo
It needs to be there or else its value isn't in settings.json.
> Update options.json.repo: put Camera Model back in

- scripts/timelapse.sh
Also, limit files to ones that start with "image-"
> Update timelapse.sh: fix: add "k" to bitrate

- html/allsky/show_thumbnails.php
> Update show_thumbnails.php: use user-supplied favicon

- scripts/timelapse.sh
Also, set variables to pass to ffmpeg to make debugging easier
> Update timelapse.sh: Don't assume name "image-*"

- scripts/upload.sh
Also, replace ( ) subshell with { }
> Update upload.sh: Add blank lines to make easier to read

- scripts/modules/allsky_overlay.py
Additional error handling to prevent errors causing the overlay to stop working
> Additional error handling

- install.sh
- scripts/flow-runner.py
- Changed install.sh to modify the way the venv is created on Bookworm
- Fixed a bug in the flow runner that would throw an exception if another exception was thrown in a module
- Added better debugging output in the flow runner if a module fails
> Fixes for Bookworm and pi 5

- html/includes/module.php
- html/includes/moduleutil.php
- html/js/modules/modules.js
Removes the option to display or hide experimental modules. Experimental modules will always be shown
> Remove experimental display option

- html/includes/system.php
> Update system.php: add Pi 5 models

- html/documentation/miscellaneous/FAQ.html
> Update FAQ.html: Better explain how to focus

- install.sh
* Also remove request for feedback - no one provided any.
* Restart daemon before mounting allsky/tmp
> Update install.sh: fix: use adduser instead of addgroup

- scripts/modules/allsky_shared.py
Reverts thomasjacquin/allsky#3211
> Revert "#3185 Fixes for locale dp separator"

- install.sh
Also:
* Indent line to make it easier to see.
* Remove newline in message.
> Update install.sh: check for missing cameramodel

- src/ASI_functions.cpp
- src/capture_ZWO.cpp
Fixes #3226 
Fix bug where histogram value wasn't divided by 3 for color images, so value could be greater than 255, thereby modifying memory outside the array.
> Capture fixes: bug fix

- allsky.sh
- config_repo/config.sh.repo
- config_repo/options.json.repo
- html/includes/createAllskyOptions.php
- html/includes/functions.php
- html/index.php
- install.sh
- scripts/check_allsky.sh
- scripts/copy_notification_image.sh
- scripts/darkSubtract.sh
- scripts/endOfDay.sh
- scripts/functions.sh
- scripts/makeChanges.sh
- scripts/postData.sh
- scripts/removeBadImages.sh
- scripts/saveImage.sh
- src/ASI_functions.cpp
- website/install.sh
Make all the settings in settings.json lowercase to avoid accidently having a setting with an upper case character but the capture programs looks for all lowercase.
> Make settings lowercase

- config_repo/configuration.json.repo
- config_repo/options.json.repo
- html/documentation/basics/Pi.html
- html/documentation/changeLog.html
- html/documentation/index.html
- html/documentation/installations/Allsky.html
- html/documentation/installations/AllskyWebsite.html
- html/documentation/js/documentation.js
- html/documentation/knownIssues.html
- html/documentation/miscellaneous/nomenclature.html
- html/documentation/settings/allsky.html
- html/documentation/troubleshooting/AllskyWebsite.html
- html/documentation/troubleshooting/ZWOCameras.html
- html/documentation/troubleshooting/hardware.html
- html/documentation/troubleshooting/reportingIssues.html
- html/index.php
- install.sh
- scripts/functions.sh
- scripts/modules/allsky_clearsky.py
- scripts/modules/allsky_export.py
- scripts/modules/allsky_loadimage.py
- scripts/modules/allsky_maskimage.py
- scripts/modules/allsky_meteor.py
- scripts/modules/allsky_pistatus.py
- scripts/modules/allsky_saveimage.py
- scripts/modules/allsky_saveintermediateimage.py
- scripts/modules/allsky_script.py
- scripts/modules/allsky_shared.py
- scripts/modules/allsky_starcount.py
- variables.sh
Several documentation pages weren't working due to the old name.  I went ahead and made the same change everywhere else.
This PR also fixes #3261 which is for a bad link.
> Change "thomasjacquin" to "AllskyTeam"

- scripts/functions.sh
- src/capture_RPi.cpp
- variables.sh
* GITHUB_ROOT and GITHUB_RAW_ROOT should not have "/allsky" at the end.  It breaks installing the Website.
* Fix bug in capture_RPi.cpp to add missing ".c_str()" to a std::string.
* Make the second error message in capture_RPi.cpp different than the first one so we can tell what caused the error.
* Ignore all the verbose output from libcamera-still - all it did was dirty the log file.
> Fix GitHub  root and others

- src/capture_RPi.cpp
Since we use system() to call libcamera-still, WIFSIGNALED() won't work since /bin/sh will almost never receive a signal.  We need to look at the return code of libcamera-still for a signal, which is in retCode.
> Update capture_RPi.cpp: fix signal handling

- README.md
- config_repo/allskyDefines.inc.repo
- html/documentation/basics/Linux.html
> Documentation improvements

- config_repo/lighttpd.conf.repo
- scripts/installUpgradeFunctions.sh
Pass it and XX_WEBSERVER_GROUP_XX to the lighttpd config file.
> Use XX_WEBSERVER_OWNER_XX

- allsky.sh
- html/includes/convertJSON.php
- install.sh
- scripts/functions.sh
- scripts/installUpgradeFunctions.sh
- src/allsky_common.cpp
- src/include/allsky_common.h
convertJSON.php and install.sh had some problems that are fixed by this PR.
> Get convertJSON.php working

- config_repo/overlay/config/overlay-RPi.json
- config_repo/overlay/config/overlay-ZWO.json
- config_repo/overlay/config/overlay.json
- html/documentation/css/custom.css
- html/includes/allskySettings.php
- html/includes/createAllskyOptions.php
- html/includes/functions.php
- scripts/makeChanges.sh
Make sure booleans are stored as   true / false  without quotes.
> Fix booleans

- html/documentation/css/custom.css
- html/includes/allskySettings.php
- html/includes/functions.php
- html/includes/liveview.php
- html/includes/status_messages.php
- html/index.php
- install.sh
Check for missing required settings and settings whose value isn't the correct type (e.g., type==number but value == abc).
Display errors and warnings at the top of the Settings page.
> Improved WebI error checking

- config_repo/options.json.repo
- html/documentation/changeLog.html
- html/documentation/settings/allsky.html
- html/includes/allskySettings.php
- html/includes/convertJSON.php
- html/includes/createAllskyOptions.php
- install.sh
- scripts/removeBadImages.sh
- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/capture_RPi.cpp
- src/capture_ZWO.cpp
- src/include/allsky_common.h
"snapshot" mode tells the camera to take a picture, then we poll the camera until the picture is complete, then we read the picture.  This appears to fix the ASI_ERROR_TIMEOUT issue!!  Let's see how it does in the field.
Fixes #3155.
> Implement ZWO snapshot mode

- html/documentation/explanations/layout.html
- html/documentation/settings/allsky.html
- html/includes/editor.php
- install.sh
- scripts/endOfNight.sh
> Decommission endOfNight_additionalSteps.sh

- src/capture_RPi.cpp
- src/capture_ZWO.cpp
And display whenever there's an error capturing an image.
This is mostly FYI and may help debugging.
Fixes #3344
> Count total capture errors

- install.sh
- scripts/functions.sh
- uninstall.sh
- upgrade.sh
Fixes #2836
Unless ${SUDO_OK} is "true" before calling functions.sh, don't let the script run under sudo.
> 2836-Check for sudo

- html/includes/configureWiFi.php
Fixes #3354
* Bug fix: do not surround "psk" value in quotes.
* Add error and warning checks.
* Add additional debugging lines.
* Add comments.
* Rename a couple variables for consistency.
> Update configureWiFi.php: bug fix with quotes

- html/documentation/css/custom.css
- html/includes/configureWiFi.php
* Bug fix: need to use toBool() with getVariableOrDefault() when returning booleans.
* Hide "Delete" button for SSID's that aren't configured, hence can't be deleted.
> configureWiFi.php changes

- allsky.sh
> Don't pass  -cmd to capture_ZWO

- allsky.sh
- config_repo/configuration.json.repo
- html/includes/convertJSON.php
- install.sh
- scripts/functions.sh
- scripts/installUpgradeFunctions.sh
- scripts/makeChanges.sh
- variables.sh
More work will be needed with the website/install.sh file, and more testing is needed.
> Update install.sh to work with Website included with Allsky

- src/capture_RPi.cpp
- src/capture_ZWO.cpp
- src/mode_mean.cpp
> 3373 create new mask when image size changes

- config_repo/options.json.repo
- html/documentation/changeLog.html
- html/documentation/settings/allsky.html
- html/includes/functions.php
- html/includes/images.php
> 3387 allow changing sort order in WebUI's Images page

- config_repo/options.json.repo
- html/documentation/changeLog.html
- html/documentation/settings/allsky.html
> 3389-allow hiding of "daytime images updated." message

- html/allsky/allsky.css
- html/allsky/functions.php
- html/allsky/index.php
- install.sh
Produce better (and correct) messages when there's a problem, like the configuration file can't be read.
> Better message when Website not configured or there's an error

- html/includes/allskySettings.php
- scripts/makeChanges.sh
makeChanges.sh doesn't do a restart so doesn't need to know if a restart is required.  The invoker will do a restart if needed.
> Don't tell makeChanges.sh about restarts

- src/capture_ZWO.cpp
In hopes of improving the ASI_ERROR_TIMEOUT issue.
Plus, keep track of when we're capturing video
> Update capture_ZWO.cpp: increase timeout on buffer flush

- config_repo/allskyDefines.inc.repo
- html/includes/editor.php
* Count the number of files that exist to determine if there's anything to edit.
* Fix determining if the remote website exists.
> Editor.php fixes

- config_repo/allskyDefines.inc.repo
- html/allsky/functions.php
- html/allsky/index.php
- html/allsky/show_thumbnails.php
- html/allsky/viewSettings.php
- html/documentation/css/custom.css
- html/includes/allskySettings.php
- html/includes/images.php
- install.sh
- scripts/functions.sh
- upgrade.sh
- variables.sh
Lots of changes to make installation of Website better.
> Fix view settings on website

- config_repo/allskyDefines.inc.repo
- html/includes/datautil.php
- html/includes/moduleutil.php
- html/includes/overlayutil.php
- html/index.php
so multiple files don't need to define it
> Move RASPI_ADMIN_DETAILS to allskyDefines.inc.repo

- config_repo/options.json.repo
> Update options.json.repo: enable Postprocessing section

- config_repo/options.json.md
It describes the fields in the options.json file.
> Upload new options.json.md file

- scripts/removeBadImages.sh
Still had old config.sh setting names.
Also, slight optimization of calling awk.
> Update removeBadImages.sh: use new setting names

- allsky.sh
- config_repo/RPi_cameraInfo.txt.repo
- html/documentation/changeLog.html
- install.sh
- scripts/functions.sh
- scripts/makeChanges.sh
- scripts/show_supported_cameras.sh
- variables.sh
Move the code in install.sh and allsk.sh that determines what cameras are connected to functions.sh and add code to verify ${CAMERA_TYPE} is a valid string and that the current camera is supported and hasn't changed unexpectedly from the last time Allsky ran.
> Centralize info on connected cameras

- allsky.sh
- src/ASI_functions.cpp
- src/allsky_common.cpp
- src/capture_RPi.cpp
- src/capture_ZWO.cpp
- src/include/allsky_common.h
These variables are set in allsky.sh and the files they point to are populated.
Currently only the CONNECTED_CAMERAS_INFO file is used.
RPi_SUPPORTED_CAMERAS (which contains information on all RPi supported cameras) will be used in a separate PR.
> Use CONNECTED_CAMERAS_INFO and RPi_SUPPORTED_CAMERAS

- html/documentation/changeLog.html
- scripts/show_supported_cameras.sh
> Fix show_supported_cameras.sh

- html/documentation/css/custom.css
- html/includes/allskySettings.php
- install.sh
- scripts/functions.sh
- scripts/postData.sh
- scripts/upload.sh
- variables.sh
Several fixes based on testing after last large set of changes to v2024.xx.xx
> Misc fixes to v2024.xx.xx

- install.sh
* Fixed remote protocol so it defaults to sftp.
* Removed unneeded trailing spaces and tabs.
* Renamed a couple variables to indicate they are for PRIOR files.
* Changed some display_msg strings to be consistent with others.
* Reworded some comments for clarity.
> Update install.sh: install.sh fixes

- html/allsky/functions.php
- html/includes/editor.php
- html/includes/functions.php
- html/includes/save_file.php
- html/index.php
- install.sh
- scripts/saveImage.sh
Various fixes after merging Alex's changes into v2024.xx.xx.
> V2024.xx.xx fixes   march 12

- html/allsky/functions.php
- html/documentation/css/custom.css
- html/includes/functions.php
- html/index.php
- scripts/makeChanges.sh
- scripts/postData.sh
Various fixes discovered during testing.
> More v2024.xx.xx fixes

- install.sh
- scripts/makeChanges.sh
- src/ASI_functions.cpp
- src/capture_RPi.cpp
- src/capture_ZWO.cpp
capture_RPi wasn't checking the results from getenv() but was using the results.
Also, makeChanges.sh didn't create the files.
> Make sure RPi camera files from getenv() exist

- scripts/functions.sh
- src/ASI_functions.cpp
- src/capture_RPi.cpp
Also includes fix for showing ZWO cameras multiple times.
> capture_RPi segmentation fault fix

- allsky.sh
- src/ASI_functions.cpp
- src/capture_RPi.cpp
- src/capture_ZWO.cpp
If "cameranumber" is in settings.json it's passed to the capture programs who set the camera number.
TODO: add "Camera Number" to the WebUI.
> Camera number fix

- config_repo/options.json.repo
- html/documentation/settings/allsky.html
- scripts/installUpgradeFunctions.sh
- scripts/upload.sh
was having a lot of issues with scp slowness to upload from my remote observatory to the other side of the world. rsync solved all my problems.
updated uploads.sh and config files to 2024 branch
> added rsync to list of upload protocols

- html/includes/module.php
- html/js/modules/modules.js
- scripts/flow-runner.py
Since we are no longer updating the module flow config files we cannot use the watchdog timer so removing it
> #3586 Remove watchdog

- scripts/check_allsky.sh
- scripts/functions.sh
- scripts/makeChanges.sh
- scripts/saveImage.sh
- scripts/timelapse.sh
Added more setting checks to makeChanges.sh - more are still needed.
> Additional makeChanges.sh checks

- allsky.sh
- html/includes/allskySettings.php
- install.sh
- scripts/copy_notification_image.sh
- scripts/functions.sh
- scripts/makeChanges.sh
- src/ASI_functions.cpp
Additional changes for multiple cameras of the same type.
More changes to come
> Multi camera changes, part 1

- config_repo/requirements-32.txt
- config_repo/requirements-64.txt
- config_repo/requirements-bookworm-32.txt
- config_repo/requirements-bookworm-64.txt
- config_repo/requirements-buster.txt
- config_repo/requirements.txt
Hotfix to remove photutils as a requirement
> #3611 Remove photutils as a requirement

- src/allsky_common.cpp
Only display after ALL options (command-line plus in config file) have been processed.
> Update allsky_common.cpp: fix: "No directory to save images"

- config_repo/RPi_cameraInfo.txt.repo
- src/ASI_functions.cpp
- src/allsky_common.cpp
* Add a new camera.
* Update some settings.
> RPi_cameraInfo.txt changes

- install.sh
- scripts/functions.sh
- scripts/installUpgradeFunctions.sh
- scripts/makeChanges.sh
- scripts/show_supported_cameras.sh
More work to come in another PR.
> Install and multi camera improvements

- scripts/darkSubtract.sh
- scripts/saveImage.sh
Only call darkSubtract.sh if we're subtracting darks.
> Dark subtract.sh optimization

- install.sh
Fixes the myTemplates folder being created in the correct location in the install script
> #3694 Fix for missing myTemplates folder

- scripts/modules/allsky_loadimage.py
Hot fix to fix image depth when loading images
> #3697 Fix for bit depth when loading images in flows

- install.sh
Work around to get Astropy installed on Buster
> #3707 Fix for Astropy on Buster

- scripts/modules/allsky_loadimage.py
Eric,
I need to revert this change from the master branch whilst I sort images in the overlay module
> #3714 Revert image change

- html/allsky/allsky.css
- html/allsky/controller.js
- html/allsky/virtualsky/virtualsky.js
Still not perfect, but better.
> Virtualsky resize fixes

- install.sh
- scripts/installUpgradeFunctions.sh
- scripts/makeChanges.sh
- scripts/updateWebsiteConfig.sh
Make sure a default local configuration.json file exists.
> Local website fixes

- html/css/overlay.css
Fixed a typo and removed a duplicate entry.
Also, used consistent indentation.
> Overlay.css changes

- config_repo/options.json.repo
- html/documentation/settings/allsky.html
- html/index.php
Improve documentation on RPi tuning files.
> Tuning file changes

- scripts/functions.sh
- scripts/makeChanges.sh
Do better job checking for valid latitude and longitude and produce better error messages.
> Latitude, longitude fixes

- html/documentation/explanations/angleSunriseSunset.html
- scripts/functions.sh
- scripts/utilities/allsky-config.sh
It shows the current daytime and nighttime start times.
> Add show_start_times to allsky-config

- scripts/modules/allsky_clearsky.py
Updated MQTT logic to be the same as the alllsky_publish module.
Tested on Homeassistant using a non SSL connection
Tested on hivemq with SSL
@thomasjacquin Ignore the Reviewer request I cant seem to remove you !!!
> #3778 Hotfix for clear sky module and mqtt

- remote_website_install.sh
- scripts/installUpgradeFunctions.sh
- variables.sh
Many updates/fixes to the remote Website installation script.
> Remote website installation updates

- config_repo/RPi_cameraInfo.txt.repo
- src/ASI_functions.cpp
> Support imx283

- install.sh
- remote_website_install.sh
- scripts/functions.sh
- scripts/installUpgradeFunctions.sh
Except for non-FTP protocols and updating existing */index.php files, this appears to work.
> Remote Website updates

- html/includes/module.php
- html/includes/overlay.php
Ensure that files are not cached between upgrades
> #3954 Improve file caching

- install.sh
> Several changes to get remote_website_install.sh working

- html/includes/functions.php
- html/index.php
Misc changes to clarify what "has" and "use" RemoteWebsite mean.
> "has" and "use" Website changes

- install.sh
Include 'dialog' in the installer dependencies
> #4014 Hotfix for missing dialog installation

- html/documentation/installations/Allsky.html
> Mention camera must be connected prior to installation

- html/documentation/installations/Allsky.html
Hope you can handle this one, Alex!!
> Update Allsky.html: correct typo

- html/documentation/installations/RemoteServer.html
> Update RemoteServer.html: warning about what page is about

- remoteWebsiteInstall.sh
> Update remoteWebsiteInstall.sh: add not about not removing images

- scripts/installUpgradeFunctions.sh
> Update installUpgradeFunctions.sh: fix comparison

- html/public.php
> Fix public.php reload

- html/includes/editor.php
> #4003 Increase timer

- html/allsky/allsky.css
- html/allsky/functions.php
- html/allsky/show_thumbnails.php
> 4111   fix Allsky Website sort order

- html/allsky/controller.js
- scripts/postData.sh
> 4114 remove streamDaytime

- scripts/modules/allsky_shared.py
Adds a new function to the shared module get_allsky_variable This takes a single parameter, variable and will attempt to find the variable either in the Allsky environment variables or the extra data files.
If the variable cannot be found then Non is returned
Testing requires attempting to read a variable in a module that was generated by anotehr module i.e.
```
variable="AS_OWWEATHER"
test = s.get_allsky_variable(variable)
print(f"{variable}={test}")`
```
> #4070 Add function to read any Allsky variable

- allsky.sh
- html/documentation/changeLog.html
- html/documentation/installations/Allsky.html
- src/allsky_common.cpp
Fixes #3823
For consistency `allsky.sh preview` is now `allsky --preview`.
Also took this opportunity to update/fix the help message from the capture programs.
> 3823 "allsky.sh --help" doesn't work

- html/allsky/allsky.css
- html/allsky/controller.js
- html/allsky/index.php
- html/allsky/virtualsky/virtualsky.js
Fixes #4151 
If the 'imageName' setting isn't correct the image won't be found.
This PR displays a message if there's an error loading the image (does not exist or isn't an image).
**@Alex-developer,
Do you know how the "error" handler can distinguish between "not found" and other errors?**
> 4151 check for missing image in website

- html/documentation/changeLog.html
- html/documentation/settings/allsky.html
- scripts/makeChanges.sh
- scripts/postToMap.sh
> 4128 bug don't allow index.php in remote website url sent to allsky map

- remoteWebsiteInstall.sh
Also:
* Run uploadTest.sh with a timeout since a couple users reported their installation hanging.
* Improved formatting of some message.
* Use LFTP_COMMANDS with all "lftp" commands.
> Update remoteWebsiteInstall.sh: move function out of subshell

- html/documentation/troubleshooting/other.html
> Update other.html: Add "git" errors

- scripts/testUpload.sh
- scripts/upload.sh
Improve the output from `testUpload.sh` to better support debugging.
> Improved test upload.sh output

- scripts/modules/allsky_shared.py
Ensures that the lat and lon are always a string before attempting to use them
> #4220 - Fix for non string lats and lons

- html/documentation/changeLog.html
- html/documentation/explanations/startrails.html
- html/documentation/sidebar.html
- scripts/utilities/allsky-config.sh
It helps users determine what to use for the `Brightness Threshold` setting.
> Add "get_brightness_info" to allsky-config

- config_repo/configuration.json.repo
Implements # 3 of [Issue #4224](https://github.com/AllskyTeam/allsky/issues/4224).
> Update configuration.json.repo: Add "meteor" link

- install.sh
- scripts/installUpgradeFunctions.sh
> 4278 prior website files being copied when they shouldnt

- html/documentation/settings/allsky.html
> Update allsky.html: Add "public" to SSH key file

- remoteWebsiteInstall.sh
- scripts/functions.sh
- scripts/installUpgradeFunctions.sh
- scripts/makeChanges.sh
- scripts/testUpload.sh
- scripts/updateJsonFile.sh
Use O_, W_, E_, and D_ scripts for output that either goes to the log file or a terminal.  (Ok, Warning, Error, Debug messages).
Use wO_ wW_, wE_, and wD_ for scripts whose output may go to the WebUI.
Use dO_, dW_, dE_, and dD_ for scripts whose output goes into a dialog box.
These functions make the code cleaner and shorter, and make it easy to change colors in the future.
> Rename shortcut functions

- install.sh
> Update install.sh: Add a message requesting users add their camera to the Allsky Map

- remoteWebsiteInstall.sh
- scripts/installUpgradeFunctions.sh
Put the dialog-related functions in `installUpgradeFunctions.sh` to aid in migrating from `whiptail` to `dialog`.
> Centralize dialog related functions

- remoteWebsiteInstall.sh
- scripts/checkFunctions.sh
- scripts/functions.sh
- scripts/installUpgradeFunctions.sh
- scripts/makeChanges.sh
- scripts/testUpload.sh
- variables.sh
Allow `makeChanges.sh` to test connectivity to a remote Website or server the same way that `remoteWebsiteInstall.sh` does.
> 4291 centralize check of web connectivity

- README.md
- scripts/utilities/showSupportedCameras.sh
This also updates the `README.md` file to mention supporting ZWO cameras purchased prior to Feb 1, 2025.
Other minor changes were made to the file as well.
> Upgrade to zwo sdk 1.37

- html/includes/functions.php
- html/includes/images.php
Check for missing 'day' in URL.
I'm not aware of any Allsky code that would do this, so perhaps a user accidently deleted it from the URL?
> 4305 WebUI's "images" page needs to check for missing day

- scripts/testUpload.sh
> Update testUpload.sh: Add "false" to fix

- html/allsky/runCommands.php
Also, change 'delete_prior_files' to 'delete_files', where the list of files to delete is passed in.
> Update runCommands.php: Add move_files()

- html/documentation/css/documentation.css
- html/documentation/explanations/timelapses.html
Add descriptions about how to change the length of the video.
> Improve timelapse documentation

- scripts/addMessage.sh
- scripts/functions.sh
- scripts/utilities/execute.sh
Instead of telling the user to execute a command, present a link for them to click on.
> Make "have been aborted" msg a link

- config_repo/requirements-32.txt
- config_repo/requirements-64.txt
- config_repo/requirements-bookworm-32.txt
- config_repo/requirements-bookworm-64.txt
- config_repo/requirements-buster.txt
- config_repo/requirements.txt
- install.sh
Tested upgrade from current master branch to this branch on
PI4
bookworm 64bit
bookworm 32bit
bullseye 32bit
PI5
bookworm 64bit
> 4404 fix for cert errors on de421bsp

- html/includes/allskySettings.php
- html/includes/functions.php
- install.sh
- remoteWebsiteInstall.sh
- scripts/checkFunctions.sh
- scripts/makeChanges.sh
- scripts/postToMap.sh
- scripts/testUpload.sh
> 4417 need better checks on remote websiteserver url and server name

- scripts/installUpgradeFunctions.sh
> Update installUpgradeFunctions.sh: Check for ALL double quotes.

- config_repo/Makefile
- config_repo/allsky.service.repo
- config_repo/allskyperiodic.service.repo
> 4490 improve the way allsky is startedrestarted

- html/includes/functions.php
- scripts/postData.sh
Don't display the "Uploaded configuration files to" messages - it just adds clutter.
Instead, put it on the console.
> Hide uploaded message

- scripts/addMessage.sh
- scripts/functions.sh
- src/allsky_common.cpp
- src/capture_RPi.cpp
- support.sh
Alex,
please review this change that fixes the "Argument list too long" error when (sometimes) running `support.sh`.
I also updated a couple .cpp files because I was too lazy to put them in a separate branch.
> 4566 support.sh can fail with Argument list too long

- html/documentation/changeLog.html
- src/capture_RPi.cpp
- src/capture_ZWO.cpp
> 4611 capture rpi needs to timeout

- html/documentation/changeLog.html
- html/includes/moduleutil.php
Alex,
Please review this fix.
If you have a better solution, please implement it.
Thanks - Eric
> 4616 moduleutilphp cant overwrite files it creates

- scripts/modules/allsky_overlay.py
- scripts/modules/allsky_shared.py
Alex,
I added a "TODO" on line 1023 of `allsky_overlay.py`.  Would you please take a look?
A use is getting that message in the log file for every image, and I have no idea what to look for to debug it.  If you could improve the warning message that would be great.
Also, per a discussion we had a while ago, all `log(0, "xxxx")` calls now call `addMessage.sh`.  Other log levels that have `sendToAllsky=True` are shown as warning messages.
Eric
> 4613 allsky shared log if level 0 or sendtoallskytrue

- scripts/darkSubtract.sh
> Update darkSubtract.sh: Add test mode

- src/allsky_common.cpp
> Update allsky_common.cpp: Output MEAN for ALL cameras

- html/includes/overlayutil.php
- html/js/overlay/oe-config.js
Replace the calls to `file_put_contents()` with calls to `updateFile()` instead, since it checks for failures due to permissions problems, and fixes the permissions.
> Use updateFile() in overlayutil.php

- allsky.sh
- scripts/copyNotificationImage.sh
- scripts/functions.sh
- variables.sh
ALLSKY_CURRENT_DIR is more descriptive since it's where the "current" image.jpg and mini-timelapse.mp4 go.
> Rename ALLSKY_CAPTURE_SAVE_DIR to ALLSKY_CURRENT_DIR

- scripts/flow-runner.py
- scripts/modules/allsky_clearsky.py
- scripts/modules/allsky_loadimage.py
- scripts/modules/allsky_maskimage.py
- scripts/modules/allsky_shared.py
- scripts/modules/allsky_starcount.py
Alex,
Displaying the line number in flow-runner.py where the error occurred is not as useful as displaying the line number in the module that caused the error.
> Improved exception handling

- install.sh
> Update install.sh: Replace message with whiptail dialog box

- html/execute.php
- html/helpers/allsky_config.php
- html/includes/allskySettings.php
- html/includes/functions.php
- html/includes/moduleutil.php
- html/includes/support.php
- html/includes/system.php
- html/index.php
- scripts/postData.sh
Using a backtick eliminates the need to check for and escape single and double quotes.
This assumes backticks aren't used in any strings.
> Use backtick with console.log()

- scripts/modules/allsky_shared.py
Also, some special characters aren't supported by my editor so get changed.  For example, the right arrow (->) character gets converted to "?" by my editor.
> Update allsky_shared.py: Fix typo

- scripts/modules/allsky_loadimage.py
Also:
* Rename a couple.
* Remove trailing spaces
> Update allsky_loadimage.py: Add variables
